[package]
name = "dtdb_relational"
version = "0.1.0"
edition = "2024"

[dependencies]
dtdb_storage = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
parking_lot = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
serde_json = "1.0"
