[package]
name = "dtdb_api"
version = "0.1.0"
edition = "2024"

[dependencies]
dtdb_storage = { workspace = true }
dtdb_relational = { workspace = true }
dtdb_sql = { workspace = true }
tonic = { workspace = true, features = ["codegen", "transport", "tls", "prost"] }
prost = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time", "net", "fs"] }
tokio-stream = { version = "0.1", features = ["net"] }
serde = { workspace = true }
bincode = { workspace = true }
futures-core = "0.3"
futures-util = { workspace = true }
pin-project = "1.0"
indexmap = { version = "2.14.0", features = ["std"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[build-dependencies]
tonic-build = "0.12"
prost-build = "0.13"

[dev-dependencies]
tempfile = { workspace = true }
