[package]
name = "dtdb_storage"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
postcard = { workspace = true }
lz4_flex = "0.13"
thiserror = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh32", "xxh3"] }
tracing = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
criterion = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh32"] }

[[bench]]
name = "storage_benchmark"
harness = false
