[package]
name = "dtdb_sql"
version = "0.1.0"
edition = "2024"

[dependencies]
dtdb_storage = { workspace = true }
dtdb_relational = { workspace = true }
sqlparser = "0.62.0"
serde = { workspace = true }
postcard = { workspace = true }
thiserror = { workspace = true }
regex = "1.12"
chrono = { workspace = true }
rust_decimal = { workspace = true }
parking_lot = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
