[package]
name = "dtdb_bindings"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
dtdb_storage = { workspace = true }
dtdb_relational = { workspace = true }
dtdb_sql = { workspace = true }
dtdb_api = { workspace = true }
cxx = "1.0"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time", "net", "fs"] }
tokio-stream = { version = "0.1", features = ["net"] }
futures-util = { workspace = true }
tonic = { workspace = true, features = ["codegen", "transport", "prost"] }

[build-dependencies]
cxx-build = "1.0"

[dev-dependencies]
tempfile = { workspace = true }
