[package]
name = "dtdb_bindings"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
dtdb_storage = { path = "../dtdb_storage" }
dtdb_relational = { path = "../dtdb_relational" }
dtdb_sql = { path = "../dtdb_sql" }
dtdb_api = { path = "../dtdb_api" }
cxx = "1.0"
tokio = { version = "1.35", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
futures-util = { version = "0.3" }
tonic = { version = "0.12", features = ["codegen", "transport"] }

[build-dependencies]
cxx-build = "1.0"
