use serde::{Deserialize, Serialize};
use dtdb_relational::{Column, DataType, Schema};
use crate::expr::Expr;

/// AggregateExpr represents aggregate functions (COUNT, SUM, MIN, MAX).
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum AggregateExpr {
    Count(Expr),
    Sum(Expr),
    Min(Expr),
    Max(Expr),
}

/// LogicalPlan represents relational algebra logical operations.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum LogicalPlan {
    Scan {
        table_name: String,
        schema: Schema,
        // Optional key range bounds (start_key, end_key) pushed down by the optimizer.
        range: Option<(dtdb_storage::DbKey, dtdb_storage::DbKey)>,
    },
    Filter {
        source: Box<LogicalPlan>,
        predicate: Expr,
    },
    Projection {
        source: Box<LogicalPlan>,
        expressions: Vec<Expr>,
        field_names: Vec<String>,
    },
    Join {
        left: Box<LogicalPlan>,
        right: Box<LogicalPlan>,
        condition: Expr,
    },
    Aggregate {
        source: Box<LogicalPlan>,
        group_by: Vec<Expr>,
        aggrs: Vec<AggregateExpr>,
        field_names: Vec<String>,
    },
    Sort {
        source: Box<LogicalPlan>,
        keys: Vec<(Expr, bool)>, // (expression, asc: true = ASC, false = DESC)
    },
    Limit {
        source: Box<LogicalPlan>,
        limit: usize,
    },
}

impl LogicalPlan {
    /// Derives the output Schema generated by this logical operator.
    pub fn schema(&self) -> Schema {
        match self {
            LogicalPlan::Scan { schema, .. } => schema.clone(),
            LogicalPlan::Filter { source, .. } | LogicalPlan::Limit { source, .. } => {
                source.schema()
            }
            LogicalPlan::Projection {
                field_names,
                source,
                expressions,
            } => {
                let source_schema = source.schema();
                let mut cols = Vec::new();
                for (name, expr) in field_names.iter().zip(expressions.iter()) {
                    let dt = match expr {
                        Expr::Literal(val) => match val {
                            dtdb_storage::DbValue::Int(_) => DataType::Int,
                            dtdb_storage::DbValue::Float(_) => DataType::Float,
                            dtdb_storage::DbValue::String(_) => DataType::String,
                            dtdb_storage::DbValue::Bytes(_) => DataType::Bytes,
                        },
                        Expr::Column(col_name) => {
                            let idx = source_schema.columns.iter().position(|col| {
                                col.name == *col_name
                                    || col_name.ends_with(&format!(".{}", col.name))
                                    || col.name.ends_with(&format!(".{}", col_name))
                            });
                            if let Some(i) = idx {
                                source_schema.columns[i].data_type
                            } else {
                                DataType::String // Fallback
                            }
                        }
                        Expr::BinaryOp { .. } => DataType::Int, // Binary comparisons return bool (Int 0 or 1)
                    };
                    cols.push(Column {
                        name: name.clone(),
                        data_type: dt,
                        is_primary_key: false,
                    });
                }
                Schema::new(cols)
            }
            LogicalPlan::Join { left, right, .. } => {
                let mut cols = left.schema().columns;
                cols.extend(right.schema().columns.clone());
                Schema::new(cols)
            }
            LogicalPlan::Aggregate {
                source,
                group_by,
                aggrs,
                field_names,
            } => {
                let source_schema = source.schema();
                let mut cols = Vec::new();

                // 1. Group-by keys.
                for (idx, expr) in group_by.iter().enumerate() {
                    let dt = match expr {
                        Expr::Column(col_name) => {
                            let pos = source_schema.columns.iter().position(|col| {
                                col.name == *col_name
                                    || col_name.ends_with(&format!(".{}", col.name))
                            });
                            if let Some(i) = pos {
                                source_schema.columns[i].data_type
                            } else {
                                DataType::String
                            }
                        }
                        _ => DataType::String,
                    };
                    cols.push(Column {
                        name: field_names[idx].clone(),
                        data_type: dt,
                        is_primary_key: false,
                    });
                }

                // 2. Aggregate functions.
                let start_idx = group_by.len();
                for (idx, aggr) in aggrs.iter().enumerate() {
                    let dt = match aggr {
                        AggregateExpr::Count(_) => DataType::Int,
                        AggregateExpr::Sum(expr) | AggregateExpr::Min(expr) | AggregateExpr::Max(expr) => {
                            match expr {
                                Expr::Column(col_name) => {
                                    let pos = source_schema.columns.iter().position(|col| {
                                        col.name == *col_name
                                            || col_name.ends_with(&format!(".{}", col.name))
                                    });
                                    if let Some(i) = pos {
                                        source_schema.columns[i].data_type
                                    } else {
                                        DataType::Float
                                    }
                                }
                                _ => DataType::Float,
                            }
                        }
                    };
                    cols.push(Column {
                        name: field_names[start_idx + idx].clone(),
                        data_type: dt,
                        is_primary_key: false,
                    });
                }

                Schema::new(cols)
            }
            LogicalPlan::Sort { source, .. } => source.schema(),
        }
    }
}

pub fn format_logical_plan(plan: &LogicalPlan) -> String {
    let mut out = String::new();
    format_logical_node(plan, 0, &mut out);
    out
}

fn format_logical_node(node: &LogicalPlan, indent: usize, out: &mut String) {
    let indent_str = "  ".repeat(indent);
    match node {
        LogicalPlan::Scan { table_name, range, .. } => {
            let range_str = match range {
                Some((s, e)) => format!("range=[{:?}, {:?}]", s, e),
                None => "range=all".to_string(),
            };
            out.push_str(&format!("{}- Scan: table={}, {}\n", indent_str, table_name, range_str));
        }
        LogicalPlan::Filter { source, predicate } => {
            out.push_str(&format!("{}- Filter: condition={:?}\n", indent_str, predicate));
            format_logical_node(source, indent + 1, out);
        }
        LogicalPlan::Projection { source, field_names, .. } => {
            out.push_str(&format!("{}- Projection: fields={:?}\n", indent_str, field_names));
            format_logical_node(source, indent + 1, out);
        }
        LogicalPlan::Join { left, right, condition } => {
            out.push_str(&format!("{}- HashJoin: condition={:?}\n", indent_str, condition));
            out.push_str(&format!("{}  left:\n", indent_str));
            format_logical_node(left, indent + 2, out);
            out.push_str(&format!("{}  right:\n", indent_str));
            format_logical_node(right, indent + 2, out);
        }
        LogicalPlan::Aggregate { source, group_by, aggrs, field_names } => {
            out.push_str(&format!(
                "{}- HashAggregate: group_by={:?}, aggregates={:?}, output_names={:?}\n",
                indent_str, group_by, aggrs, field_names
            ));
            format_logical_node(source, indent + 1, out);
        }
        LogicalPlan::Sort { source, keys } => {
            let keys_str: Vec<String> = keys
                .iter()
                .map(|(expr, asc)| format!("{:?} {}", expr, if *asc { "ASC" } else { "DESC" }))
                .collect();
            out.push_str(&format!("{}- Sort: keys={:?}\n", indent_str, keys_str));
            format_logical_node(source, indent + 1, out);
        }
        LogicalPlan::Limit { source, limit } => {
            out.push_str(&format!("{}- Limit: count={}\n", indent_str, limit));
            format_logical_node(source, indent + 1, out);
        }
    }
}
