use crate::expr::Expr;
use crate::logical::{AggregateExpr, JoinType, SetOpType};
use dtdb_relational::{Row, Schema};
use dtdb_storage::DbValue;
use std::collections::HashMap;

/// PhysicalOperator defines the Volcano Iterator interface for query execution.
pub trait PhysicalOperator {
    /// Returns the next row in the stream, or `None` if the stream is exhausted.
    fn next(&mut self) -> Result<Option<Row>, String>;

    /// Returns the output Schema generated by this operator.
    fn schema(&self) -> &Schema;

    /// Formats the operator tree recursively for explanation.
    fn explain(&self, indent: usize, out: &mut String);
}

// ==========================================
// 1. SeqScan Physical Operator
// ==========================================
pub struct PhysicalSeqScan {
    schema: Schema,
    rows_iter: std::vec::IntoIter<Row>,
}

impl PhysicalSeqScan {
    pub fn new(schema: Schema, rows: Vec<Row>) -> Self {
        Self {
            schema,
            rows_iter: rows.into_iter(),
        }
    }
}

impl PhysicalOperator for PhysicalSeqScan {
    fn next(&mut self) -> Result<Option<Row>, String> {
        Ok(self.rows_iter.next())
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSeqScan: schema={:?}\n",
            "  ".repeat(indent),
            self.schema
        ));
    }
}

// ==========================================
// 1.5. IndexScan Physical Operator
// ==========================================
pub struct PhysicalIndexScan {
    schema: Schema,
    rows_iter: std::vec::IntoIter<Row>,
}

impl PhysicalIndexScan {
    pub fn new(schema: Schema, rows: Vec<Row>) -> Self {
        Self {
            schema,
            rows_iter: rows.into_iter(),
        }
    }
}

impl PhysicalOperator for PhysicalIndexScan {
    fn next(&mut self) -> Result<Option<Row>, String> {
        Ok(self.rows_iter.next())
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalIndexScan: schema={:?}\n",
            "  ".repeat(indent),
            self.schema
        ));
    }
}

// ==========================================
// 2. Filter Physical Operator
// ==========================================
pub struct PhysicalFilter {
    source: Box<dyn PhysicalOperator>,
    predicate: Expr,
}

impl PhysicalFilter {
    pub fn new(source: Box<dyn PhysicalOperator>, predicate: Expr) -> Self {
        Self { source, predicate }
    }
}

impl PhysicalOperator for PhysicalFilter {
    fn next(&mut self) -> Result<Option<Row>, String> {
        while let Some(row) = self.source.next()? {
            let res = self.predicate.eval(&row, self.source.schema())?;
            match res {
                DbValue::Bool(b) if b => return Ok(Some(row)),
                DbValue::Int(v) if v != 0 => return Ok(Some(row)),
                _ => {} // Skip row
            }
        }
        Ok(None)
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalFilter: predicate={:?}\n",
            "  ".repeat(indent),
            self.predicate
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 3. Projection Physical Operator
// ==========================================
pub struct PhysicalProjection {
    source: Box<dyn PhysicalOperator>,
    expressions: Vec<Expr>,
    schema: Schema,
}

impl PhysicalProjection {
    pub fn new(source: Box<dyn PhysicalOperator>, expressions: Vec<Expr>, schema: Schema) -> Self {
        Self {
            source,
            expressions,
            schema,
        }
    }
}

impl PhysicalOperator for PhysicalProjection {
    fn next(&mut self) -> Result<Option<Row>, String> {
        if let Some(row) = self.source.next()? {
            let mut projected_vals = Vec::new();
            let source_schema = self.source.schema();
            for expr in &self.expressions {
                projected_vals.push(expr.eval(&row, source_schema)?);
            }
            Ok(Some(Row::new(projected_vals)))
        } else {
            Ok(None)
        }
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalProjection: expressions={:?}\n",
            "  ".repeat(indent),
            self.expressions
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 4. Limit Physical Operator
// ==========================================
pub struct PhysicalLimit {
    source: Box<dyn PhysicalOperator>,
    limit: Option<usize>,
    offset: usize,
    skipped: usize,
    returned: usize,
}

impl PhysicalLimit {
    pub fn new(source: Box<dyn PhysicalOperator>, limit: Option<usize>, offset: usize) -> Self {
        Self {
            source,
            limit,
            offset,
            skipped: 0,
            returned: 0,
        }
    }
}

impl PhysicalOperator for PhysicalLimit {
    fn next(&mut self) -> Result<Option<Row>, String> {
        // Skip offset rows first
        while self.skipped < self.offset {
            if self.source.next()?.is_none() {
                return Ok(None);
            }
            self.skipped += 1;
        }

        if let Some(lim) = self.limit
            && self.returned >= lim
        {
            return Ok(None);
        }

        if let Some(row) = self.source.next()? {
            self.returned += 1;
            Ok(Some(row))
        } else {
            Ok(None)
        }
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        let limit_str = match self.limit {
            Some(l) => l.to_string(),
            None => "none".to_string(),
        };
        out.push_str(&format!(
            "{}- PhysicalLimit: limit={}, offset={}\n",
            "  ".repeat(indent),
            limit_str,
            self.offset
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 5. Sort Physical Operator (Pipeline-Blocking)
// ==========================================
pub struct PhysicalSort {
    source: Box<dyn PhysicalOperator>,
    keys: Vec<(Expr, bool)>, // (expression, asc)
    sorted_rows: Option<std::vec::IntoIter<Row>>,
}

impl PhysicalSort {
    pub fn new(source: Box<dyn PhysicalOperator>, keys: Vec<(Expr, bool)>) -> Self {
        Self {
            source,
            keys,
            sorted_rows: None,
        }
    }
}

impl PhysicalOperator for PhysicalSort {
    fn next(&mut self) -> Result<Option<Row>, String> {
        if self.sorted_rows.is_none() {
            // Blocking phase: consume all rows from source and sort them
            let mut rows = Vec::new();
            while let Some(row) = self.source.next()? {
                rows.push(row);
            }

            let source_schema = self.source.schema();
            let mut err = None;

            rows.sort_by(|a, b| {
                for (expr, asc) in &self.keys {
                    let a_val = match expr.eval(a, source_schema) {
                        Ok(v) => v,
                        Err(e) => {
                            err = Some(e);
                            return std::cmp::Ordering::Equal;
                        }
                    };
                    let b_val = match expr.eval(b, source_schema) {
                        Ok(v) => v,
                        Err(e) => {
                            err = Some(e);
                            return std::cmp::Ordering::Equal;
                        }
                    };
                    match compare_values(&a_val, &b_val) {
                        Ok(ord) => {
                            if ord != std::cmp::Ordering::Equal {
                                return if *asc { ord } else { ord.reverse() };
                            }
                        }
                        Err(e) => {
                            err = Some(e);
                            return std::cmp::Ordering::Equal;
                        }
                    }
                }
                std::cmp::Ordering::Equal
            });

            if let Some(e) = err {
                return Err(e);
            }

            self.sorted_rows = Some(rows.into_iter());
        }

        Ok(self.sorted_rows.as_mut().unwrap().next())
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        let keys_str: Vec<String> = self
            .keys
            .iter()
            .map(|(expr, asc)| format!("{:?} {}", expr, if *asc { "ASC" } else { "DESC" }))
            .collect();
        out.push_str(&format!(
            "{}- PhysicalSort: keys={:?}\n",
            "  ".repeat(indent),
            keys_str
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 6. HashJoin Physical Operator (Semi-Blocking)
// ==========================================
pub struct PhysicalHashJoin {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    left_on: Expr,
    right_on: Expr,
    join_type: JoinType,
    schema: Schema,
    // Build phase hash map: DbValue representation of join key -> Right Rows
    hash_table: Option<HashMap<DbValue, Vec<Row>>>,
    // Buffer to hold joined rows from the current probe row
    join_buffer: Vec<Row>,
}

impl PhysicalHashJoin {
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        left_on: Expr,
        right_on: Expr,
        join_type: JoinType,
        schema: Schema,
    ) -> Self {
        Self {
            left,
            right,
            left_on,
            right_on,
            join_type,
            schema,
            hash_table: None,
            join_buffer: Vec::new(),
        }
    }
}

impl PhysicalOperator for PhysicalHashJoin {
    fn next(&mut self) -> Result<Option<Row>, String> {
        // If there are rows buffered from the previous probe match, yield them
        if !self.join_buffer.is_empty() {
            return Ok(Some(self.join_buffer.remove(0)));
        }

        // Build phase: read all right rows into the hash table
        if self.hash_table.is_none() {
            let mut table = HashMap::new();
            let right_schema = self.right.schema().clone();
            while let Some(row) = self.right.next()? {
                let key_val = self.right_on.eval(&row, &right_schema)?;
                if key_val != DbValue::Null {
                    table.entry(key_val).or_insert_with(Vec::new).push(row);
                }
            }
            self.hash_table = Some(table);
        }

        let hash_table = self.hash_table.as_ref().unwrap();
        let left_schema = self.left.schema().clone();
        let right_schema = self.right.schema().clone();

        // Probe phase: stream left rows one by one
        while let Some(left_row) = self.left.next()? {
            let key_val = self.left_on.eval(&left_row, &left_schema)?;

            if key_val != DbValue::Null {
                if let Some(right_rows) = hash_table.get(&key_val) {
                    // Generate joined rows: combine left row fields + right row fields
                    for right_row in right_rows {
                        let mut merged_values = left_row.values.clone();
                        merged_values.extend(right_row.values.clone());
                        self.join_buffer.push(Row::new(merged_values));
                    }
                } else if self.join_type == JoinType::Left {
                    // Left outer join mismatch: pad right columns with NULL values
                    let mut merged_values = left_row.values.clone();
                    for _ in &right_schema.columns {
                        merged_values.push(DbValue::Null);
                    }
                    self.join_buffer.push(Row::new(merged_values));
                }
            } else if self.join_type == JoinType::Left {
                // Left outer join mismatch: pad right columns with NULL values
                let mut merged_values = left_row.values.clone();
                for _ in &right_schema.columns {
                    merged_values.push(DbValue::Null);
                }
                self.join_buffer.push(Row::new(merged_values));
            }

            if !self.join_buffer.is_empty() {
                return Ok(Some(self.join_buffer.remove(0)));
            }
        }

        Ok(None)
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalHashJoin: type={:?}, left_on={:?}, right_on={:?}\n",
            "  ".repeat(indent),
            self.join_type,
            self.left_on,
            self.right_on
        ));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}

// ==========================================
// 6.5. CrossJoin Physical Operator (Cartesian Product)
// ==========================================
pub struct PhysicalCrossJoin {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    schema: Schema,
    // Build phase buffer: read all right rows into memory
    right_rows: Option<Vec<Row>>,
    // Buffer to hold joined rows from the current probe row
    join_buffer: Vec<Row>,
}

impl PhysicalCrossJoin {
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        schema: Schema,
    ) -> Self {
        Self {
            left,
            right,
            schema,
            right_rows: None,
            join_buffer: Vec::new(),
        }
    }
}

impl PhysicalOperator for PhysicalCrossJoin {
    fn next(&mut self) -> Result<Option<Row>, String> {
        // If there are rows buffered from the previous probe match, yield them
        if !self.join_buffer.is_empty() {
            return Ok(Some(self.join_buffer.remove(0)));
        }

        // Build phase: read all right rows into memory
        if self.right_rows.is_none() {
            let mut rows = Vec::new();
            while let Some(row) = self.right.next()? {
                rows.push(row);
            }
            self.right_rows = Some(rows);
        }

        let right_rows = self.right_rows.as_ref().unwrap();

        // Probe phase: stream left rows one by one
        while let Some(left_row) = self.left.next()? {
            for right_row in right_rows {
                let mut merged_values = left_row.values.clone();
                merged_values.extend(right_row.values.clone());
                self.join_buffer.push(Row::new(merged_values));
            }

            if !self.join_buffer.is_empty() {
                return Ok(Some(self.join_buffer.remove(0)));
            }
        }

        Ok(None)
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!("{}- PhysicalCrossJoin\n", "  ".repeat(indent)));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}

// ==========================================
// 7. HashAggregate Physical Operator (Pipeline-Blocking)
// ==========================================
pub struct PhysicalHashAggregate {
    source: Box<dyn PhysicalOperator>,
    group_by: Vec<Expr>,
    aggrs: Vec<AggregateExpr>,
    schema: Schema,
    aggregated_rows: Option<std::vec::IntoIter<Row>>,
}

impl PhysicalHashAggregate {
    pub fn new(
        source: Box<dyn PhysicalOperator>,
        group_by: Vec<Expr>,
        aggrs: Vec<AggregateExpr>,
        schema: Schema,
    ) -> Self {
        Self {
            source,
            group_by,
            aggrs,
            schema,
            aggregated_rows: None,
        }
    }
}

impl PhysicalOperator for PhysicalHashAggregate {
    fn next(&mut self) -> Result<Option<Row>, String> {
        if self.aggregated_rows.is_none() {
            // Blocking phase: group and accumulate aggregates for all source rows
            let mut groups: HashMap<Vec<DbValue>, Vec<Accumulator>> = HashMap::new();

            let source_schema = self.source.schema().clone();

            while let Some(row) = self.source.next()? {
                // 1. Compute group-by values
                let mut group_vals = Vec::new();
                for expr in &self.group_by {
                    let val = expr.eval(&row, &source_schema)?;
                    group_vals.push(val);
                }

                // 2. Initialize accumulators if group is seen for the first time
                let accumulators = groups.entry(group_vals).or_insert_with(|| {
                    self.aggrs
                        .iter()
                        .map(|aggr| match aggr {
                            AggregateExpr::Count(_) => Accumulator::Count { count: 0 },
                            AggregateExpr::Sum(_) => Accumulator::Sum { sum: None },
                            AggregateExpr::Min(_) => Accumulator::Min { min: None },
                            AggregateExpr::Max(_) => Accumulator::Max { max: None },
                            AggregateExpr::Avg(_) => Accumulator::Avg { sum: 0.0, count: 0 },
                        })
                        .collect()
                });

                // 3. Update accumulators with column values
                for (idx, aggr) in self.aggrs.iter().enumerate() {
                    let val = match aggr {
                        AggregateExpr::Count(expr)
                        | AggregateExpr::Sum(expr)
                        | AggregateExpr::Min(expr)
                        | AggregateExpr::Max(expr)
                        | AggregateExpr::Avg(expr) => expr.eval(&row, &source_schema)?,
                    };
                    accumulators[idx].update(&val)?;
                }
            }

            // 4. Construct final output rows
            let mut output_rows = Vec::new();
            for (group_vals, accumulators) in groups {
                let mut row_vals = group_vals; // starts with group-by keys
                for acc in accumulators {
                    row_vals.push(acc.finalize());
                }
                output_rows.push(Row::new(row_vals));
            }

            self.aggregated_rows = Some(output_rows.into_iter());
        }

        Ok(self.aggregated_rows.as_mut().unwrap().next())
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalHashAggregate: group_by={:?}, aggrs={:?}\n",
            "  ".repeat(indent),
            self.group_by,
            self.aggrs
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// Aggregation State Accumulators
// ==========================================
enum Accumulator {
    Count { count: i64 },
    Sum { sum: Option<f64> },
    Min { min: Option<DbValue> },
    Max { max: Option<DbValue> },
    Avg { sum: f64, count: i64 },
}

impl Accumulator {
    fn update(&mut self, val: &DbValue) -> Result<(), String> {
        if matches!(val, DbValue::Null) {
            return Ok(()); // Ignore NULL values for all aggregates
        }
        match self {
            Accumulator::Count { count } => {
                *count += 1;
            }
            Accumulator::Sum { sum } => {
                let s = sum.get_or_insert(0.0);
                match val {
                    DbValue::Int(v) => *s += *v as f64,
                    DbValue::Float(v) => *s += *v,
                    other => {
                        return Err(format!(
                            "Cannot compute SUM on non-numeric value {:?}",
                            other
                        ));
                    }
                }
            }
            Accumulator::Min { min } => match min {
                Some(m) => {
                    let ord = compare_values(val, m)?;
                    if ord == std::cmp::Ordering::Less {
                        *min = Some(val.clone());
                    }
                }
                None => *min = Some(val.clone()),
            },
            Accumulator::Max { max } => match max {
                Some(m) => {
                    let ord = compare_values(val, m)?;
                    if ord == std::cmp::Ordering::Greater {
                        *max = Some(val.clone());
                    }
                }
                None => *max = Some(val.clone()),
            },
            Accumulator::Avg { sum, count } => {
                match val {
                    DbValue::Int(v) => *sum += *v as f64,
                    DbValue::Float(v) => *sum += *v,
                    other => {
                        return Err(format!(
                            "Cannot compute AVG on non-numeric value {:?}",
                            other
                        ));
                    }
                }
                *count += 1;
            }
        }
        Ok(())
    }

    fn finalize(&self) -> DbValue {
        match self {
            Accumulator::Count { count } => DbValue::Int(*count),
            Accumulator::Sum { sum } => sum.map(DbValue::Float).unwrap_or(DbValue::Null),
            Accumulator::Min { min } => min.clone().unwrap_or(DbValue::Null),
            Accumulator::Max { max } => max.clone().unwrap_or(DbValue::Null),
            Accumulator::Avg { sum, count } => {
                if *count == 0 {
                    DbValue::Null
                } else {
                    DbValue::Float(*sum / (*count as f64))
                }
            }
        }
    }
}

// ==========================================
// Helper Utility Functions
// ==========================================

fn compare_values(l: &DbValue, r: &DbValue) -> Result<std::cmp::Ordering, String> {
    match (l, r) {
        (DbValue::Null, DbValue::Null) => Ok(std::cmp::Ordering::Equal),
        (DbValue::Null, _) => Ok(std::cmp::Ordering::Less),
        (_, DbValue::Null) => Ok(std::cmp::Ordering::Greater),
        (DbValue::Int(lv), DbValue::Int(rv)) => Ok(lv.cmp(rv)),
        (DbValue::Float(lv), DbValue::Float(rv)) => lv
            .partial_cmp(rv)
            .ok_or_else(|| "NaN float comparison".to_string()),
        (DbValue::Int(lv), DbValue::Float(rv)) => (*lv as f64)
            .partial_cmp(rv)
            .ok_or_else(|| "NaN float comparison".to_string()),
        (DbValue::Float(lv), DbValue::Int(rv)) => lv
            .partial_cmp(&(*rv as f64))
            .ok_or_else(|| "NaN float comparison".to_string()),
        (DbValue::String(lv), DbValue::String(rv)) => Ok(lv.cmp(rv)),
        (DbValue::Bytes(lv), DbValue::Bytes(rv)) => Ok(lv.cmp(rv)),
        (DbValue::Bool(lv), DbValue::Bool(rv)) => Ok(lv.cmp(rv)),
        (expected, actual) => Err(format!(
            "Type mismatch: cannot compare {:?} and {:?}",
            expected, actual
        )),
    }
}

// ==========================================
// Set Operation Physical Operator (UNION, INTERSECT, EXCEPT)
// ==========================================
pub enum SetOpState {
    Init,
    UnionDistinct {
        seen: std::collections::HashSet<Row>,
        reading_left: bool,
    },
    UnionAll {
        reading_left: bool,
    },
    Intersect {
        right_counts: std::collections::HashMap<Row, usize>,
        seen: std::collections::HashSet<Row>,
    },
    Except {
        right_counts: std::collections::HashMap<Row, usize>,
        seen: std::collections::HashSet<Row>,
    },
}

pub struct PhysicalSetOp {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    op: SetOpType,
    all: bool,
    schema: Schema,
    state: SetOpState,
}

impl PhysicalSetOp {
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        op: SetOpType,
        all: bool,
        schema: Schema,
    ) -> Self {
        Self {
            left,
            right,
            op,
            all,
            schema,
            state: SetOpState::Init,
        }
    }
}

impl PhysicalOperator for PhysicalSetOp {
    fn next(&mut self) -> Result<Option<Row>, String> {
        if matches!(self.state, SetOpState::Init) {
            match self.op {
                SetOpType::Union => {
                    if self.all {
                        self.state = SetOpState::UnionAll { reading_left: true };
                    } else {
                        self.state = SetOpState::UnionDistinct {
                            seen: std::collections::HashSet::new(),
                            reading_left: true,
                        };
                    }
                }
                SetOpType::Intersect => {
                    let mut right_counts = std::collections::HashMap::new();
                    while let Some(row) = self.right.next()? {
                        *right_counts.entry(row).or_insert(0) += 1;
                    }
                    self.state = SetOpState::Intersect {
                        right_counts,
                        seen: std::collections::HashSet::new(),
                    };
                }
                SetOpType::Except => {
                    let mut right_counts = std::collections::HashMap::new();
                    while let Some(row) = self.right.next()? {
                        *right_counts.entry(row).or_insert(0) += 1;
                    }
                    self.state = SetOpState::Except {
                        right_counts,
                        seen: std::collections::HashSet::new(),
                    };
                }
            }
        }

        match &mut self.state {
            SetOpState::UnionAll { reading_left } => {
                if *reading_left {
                    if let Some(row) = self.left.next()? {
                        return Ok(Some(row));
                    }
                    *reading_left = false;
                }
                self.right.next()
            }
            SetOpState::UnionDistinct { seen, reading_left } => {
                if *reading_left {
                    while let Some(row) = self.left.next()? {
                        if seen.insert(row.clone()) {
                            return Ok(Some(row));
                        }
                    }
                    *reading_left = false;
                }
                while let Some(row) = self.right.next()? {
                    if seen.insert(row.clone()) {
                        return Ok(Some(row));
                    }
                }
                Ok(None)
            }
            SetOpState::Intersect { right_counts, seen } => {
                while let Some(row) = self.left.next()? {
                    if self.all {
                        if let Some(count) = right_counts.get_mut(&row).filter(|c| **c > 0) {
                            *count -= 1;
                            return Ok(Some(row));
                        }
                    } else if right_counts.contains_key(&row) && seen.insert(row.clone()) {
                        return Ok(Some(row));
                    }
                }
                Ok(None)
            }
            SetOpState::Except { right_counts, seen } => {
                while let Some(row) = self.left.next()? {
                    if self.all {
                        if let Some(count) = right_counts.get_mut(&row).filter(|c| **c > 0) {
                            *count -= 1;
                            continue;
                        }
                        return Ok(Some(row));
                    } else if !right_counts.contains_key(&row) && seen.insert(row.clone()) {
                        return Ok(Some(row));
                    }
                }
                Ok(None)
            }
            SetOpState::Init => unreachable!(),
        }
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSetOp: op={:?}, all={}\n",
            "  ".repeat(indent),
            self.op,
            self.all
        ));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}
