use crate::expr::{Expr, compare_values};
use crate::logical::{AggregateExpr, JoinType, SetOpType};
use dtdb_relational::{Row, Schema};
use dtdb_storage::DbValue;
use std::collections::BinaryHeap;
use std::collections::HashMap;
use std::collections::HashSet;
use std::fs::File;
use std::io::{BufReader, BufWriter, Write};
use std::path::PathBuf;
use std::sync::Arc;

/// PhysicalOperator defines the Volcano Iterator interface for query execution.
pub trait PhysicalOperator {
    /// Returns the next row in the stream, or `None` if the stream is exhausted.
    fn next(&mut self) -> Result<Option<Row>, String>;

    /// Returns the output Schema generated by this operator.
    fn schema(&self) -> &Schema;

    /// Formats the operator tree recursively for explanation.
    fn explain(&self, indent: usize, out: &mut String);
}

// ==========================================
// 1. SeqScan Physical Operator
// ==========================================
pub struct PhysicalSeqScan {
    schema: Schema,
    source: Box<dyn Iterator<Item = Result<Row, String>>>,
}

impl PhysicalSeqScan {
    pub fn new(schema: Schema, rows: Vec<Row>) -> Self {
        Self {
            schema,
            source: Box::new(rows.into_iter().map(Ok)),
        }
    }

    pub fn from_iter(
        schema: Schema,
        source: Box<dyn Iterator<Item = Result<Row, String>>>,
    ) -> Self {
        Self { schema, source }
    }
}

impl PhysicalOperator for PhysicalSeqScan {
    fn next(&mut self) -> Result<Option<Row>, String> {
        self.source.next().transpose()
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSeqScan: schema={:?}\n",
            "  ".repeat(indent),
            self.schema
        ));
    }
}

// ==========================================
// 1.5. IndexScan Physical Operator
// ==========================================
pub struct PhysicalIndexScan {
    schema: Schema,
    source: Box<dyn Iterator<Item = Result<Row, String>>>,
}

impl PhysicalIndexScan {
    pub fn new(schema: Schema, rows: Vec<Row>) -> Self {
        Self {
            schema,
            source: Box::new(rows.into_iter().map(Ok)),
        }
    }

    pub fn from_iter(
        schema: Schema,
        source: Box<dyn Iterator<Item = Result<Row, String>>>,
    ) -> Self {
        Self { schema, source }
    }
}

impl PhysicalOperator for PhysicalIndexScan {
    fn next(&mut self) -> Result<Option<Row>, String> {
        self.source.next().transpose()
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalIndexScan: schema={:?}\n",
            "  ".repeat(indent),
            self.schema
        ));
    }
}

// ==========================================
// 1.7. FullTextScan Physical Operator
// ==========================================
pub struct PhysicalFullTextScan {
    schema: Schema,
    query_str: String,
    source: Box<dyn Iterator<Item = Result<Row, String>>>,
}

impl PhysicalFullTextScan {
    pub fn new(schema: Schema, query_str: String, rows: Vec<Row>) -> Self {
        Self {
            schema,
            query_str,
            source: Box::new(rows.into_iter().map(Ok)),
        }
    }
}

impl PhysicalOperator for PhysicalFullTextScan {
    fn next(&mut self) -> Result<Option<Row>, String> {
        self.source.next().transpose()
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalFullTextScan: query={:?}, schema={:?}\n",
            "  ".repeat(indent),
            self.query_str,
            self.schema
        ));
    }
}

// ==========================================
// 2. Filter Physical Operator
// ==========================================
pub struct PhysicalFilter {
    source: Box<dyn PhysicalOperator>,
    predicate: Expr,
}

impl PhysicalFilter {
    pub fn new(source: Box<dyn PhysicalOperator>, predicate: Expr) -> Self {
        Self { source, predicate }
    }
}

impl PhysicalOperator for PhysicalFilter {
    fn next(&mut self) -> Result<Option<Row>, String> {
        while let Some(row) = self.source.next()? {
            let res = self.predicate.eval(&row, self.source.schema())?;
            match res {
                DbValue::Bool(b) if b => return Ok(Some(row)),
                DbValue::Int(v) if v != 0 => return Ok(Some(row)),
                _ => {} // Skip row
            }
        }
        Ok(None)
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalFilter: predicate={:?}\n",
            "  ".repeat(indent),
            self.predicate
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 3. Projection Physical Operator
// ==========================================
pub struct PhysicalProjection {
    source: Box<dyn PhysicalOperator>,
    expressions: Vec<Expr>,
    schema: Schema,
}

impl PhysicalProjection {
    pub fn new(source: Box<dyn PhysicalOperator>, expressions: Vec<Expr>, schema: Schema) -> Self {
        Self {
            source,
            expressions,
            schema,
        }
    }
}

impl PhysicalOperator for PhysicalProjection {
    fn next(&mut self) -> Result<Option<Row>, String> {
        if let Some(row) = self.source.next()? {
            let mut projected_vals = Vec::new();
            let source_schema = self.source.schema();
            for expr in &self.expressions {
                projected_vals.push(expr.eval(&row, source_schema)?);
            }
            Ok(Some(Row::new(projected_vals)))
        } else {
            Ok(None)
        }
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalProjection: expressions={:?}\n",
            "  ".repeat(indent),
            self.expressions
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 4. Limit Physical Operator
// ==========================================
pub struct PhysicalLimit {
    source: Box<dyn PhysicalOperator>,
    limit: Option<usize>,
    offset: usize,
    skipped: usize,
    returned: usize,
}

impl PhysicalLimit {
    pub fn new(source: Box<dyn PhysicalOperator>, limit: Option<usize>, offset: usize) -> Self {
        Self {
            source,
            limit,
            offset,
            skipped: 0,
            returned: 0,
        }
    }
}

impl PhysicalOperator for PhysicalLimit {
    fn next(&mut self) -> Result<Option<Row>, String> {
        // Skip offset rows first
        while self.skipped < self.offset {
            if self.source.next()?.is_none() {
                return Ok(None);
            }
            self.skipped += 1;
        }

        if let Some(lim) = self.limit
            && self.returned >= lim
        {
            return Ok(None);
        }

        if let Some(row) = self.source.next()? {
            self.returned += 1;
            Ok(Some(row))
        } else {
            Ok(None)
        }
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        let limit_str = match self.limit {
            Some(l) => l.to_string(),
            None => "none".to_string(),
        };
        out.push_str(&format!(
            "{}- PhysicalLimit: limit={}, offset={}\n",
            "  ".repeat(indent),
            limit_str,
            self.offset
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 5. Sort Physical Operator (Pipeline-Blocking)
// ==========================================
/// A sorted run stored as a temporary file on disk.
struct SortedRun {
    path: PathBuf,
    reader: Option<BufReader<File>>,
    peeked: Option<(Vec<DbValue>, Row)>,
    remaining: usize,
}

impl SortedRun {
    fn new(path: PathBuf, count: usize) -> Self {
        Self {
            path,
            reader: None,
            peeked: None,
            remaining: count,
        }
    }

    fn open(&mut self) -> Result<(), String> {
        let file = File::open(&self.path)
            .map_err(|e| format!("Failed to open temp file {:?}: {}", self.path, e))?;
        let mut reader = BufReader::new(file);
        let count: u64 = bincode::deserialize_from(&mut reader)
            .map_err(|e| format!("Failed to read count from run file: {}", e))?;
        self.remaining = count as usize;
        self.reader = Some(reader);
        self.advance()?;
        Ok(())
    }

    fn advance(&mut self) -> Result<(), String> {
        if self.remaining == 0 {
            self.peeked = None;
            self.reader = None; // Close file handle early
            return Ok(());
        }

        let reader = self.reader.as_mut().ok_or("Advance called on closed run")?;
        let keys: Vec<DbValue> = bincode::deserialize_from(&mut *reader)
            .map_err(|e| format!("Failed to deserialize keys: {}", e))?;
        let row: Row = bincode::deserialize_from(&mut *reader)
            .map_err(|e| format!("Failed to deserialize row: {}", e))?;

        self.peeked = Some((keys, row));
        self.remaining -= 1;
        Ok(())
    }
}

impl Drop for SortedRun {
    fn drop(&mut self) {
        self.reader = None; // Explicitly drop the reader to release the file lock
        let _ = std::fs::remove_file(&self.path);
    }
}

struct HeapEntry {
    sort_keys: Vec<DbValue>,
    row: Row,
    run_index: usize,
    directions: Arc<Vec<bool>>,
    error_slot: Arc<std::sync::Mutex<Option<String>>>,
}

impl Ord for HeapEntry {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        for (idx, &asc) in self.directions.iter().enumerate() {
            let a_val = &self.sort_keys[idx];
            let b_val = &other.sort_keys[idx];
            match compare_values(a_val, b_val) {
                Ok(ord) => {
                    if ord != std::cmp::Ordering::Equal {
                        return if asc { ord.reverse() } else { ord };
                    }
                }
                Err(e) => {
                    if let Ok(mut guard) = self.error_slot.lock() {
                        let _ = guard.get_or_insert(e);
                    }
                    return std::cmp::Ordering::Equal;
                }
            }
        }
        std::cmp::Ordering::Equal
    }
}

impl PartialOrd for HeapEntry {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl PartialEq for HeapEntry {
    fn eq(&self, other: &Self) -> bool {
        self.cmp(other) == std::cmp::Ordering::Equal
    }
}

impl Eq for HeapEntry {}

struct KWayMerge {
    heap: BinaryHeap<HeapEntry>,
    runs: Vec<SortedRun>,
    directions: Arc<Vec<bool>>,
    error_slot: Arc<std::sync::Mutex<Option<String>>>,
}

impl KWayMerge {
    fn new(mut runs: Vec<SortedRun>, keys: &[(Expr, bool)]) -> Result<Self, String> {
        let directions = Arc::new(keys.iter().map(|(_, asc)| *asc).collect::<Vec<_>>());
        let error_slot = Arc::new(std::sync::Mutex::new(None));
        let mut heap = BinaryHeap::new();

        for (idx, run) in runs.iter_mut().enumerate() {
            run.open()?;
            if let Some((sort_keys, row)) = run.peeked.take() {
                heap.push(HeapEntry {
                    sort_keys,
                    row,
                    run_index: idx,
                    directions: Arc::clone(&directions),
                    error_slot: Arc::clone(&error_slot),
                });
            }
        }

        Ok(Self {
            heap,
            runs,
            directions,
            error_slot,
        })
    }

    fn next(&mut self) -> Result<Option<Row>, String> {
        if let Some(err) = self.error_slot.lock().ok().and_then(|g| g.clone()) {
            return Err(err);
        }

        let entry = match self.heap.pop() {
            Some(e) => e,
            None => return Ok(None),
        };

        let run_idx = entry.run_index;
        self.runs[run_idx].advance()?;

        if let Some((sort_keys, row)) = self.runs[run_idx].peeked.take() {
            self.heap.push(HeapEntry {
                sort_keys,
                row,
                run_index: run_idx,
                directions: Arc::clone(&self.directions),
                error_slot: Arc::clone(&self.error_slot),
            });
        }

        Ok(Some(entry.row))
    }
}

enum MergeState {
    InMemory(std::vec::IntoIter<Row>),
    External(KWayMerge),
}

fn estimate_row_size(keys: &[DbValue], row: &Row) -> usize {
    let mut size = std::mem::size_of::<Row>() + row.values.len() * std::mem::size_of::<DbValue>();
    for val in &row.values {
        size += match val {
            DbValue::String(s) => s.len(),
            DbValue::Bytes(b) => b.len(),
            _ => 0,
        };
    }
    size += std::mem::size_of::<Vec<DbValue>>() + std::mem::size_of_val(keys);
    for val in keys {
        size += match val {
            DbValue::String(s) => s.len(),
            DbValue::Bytes(b) => b.len(),
            _ => 0,
        };
    }
    size
}

pub struct PhysicalSort {
    source: Box<dyn PhysicalOperator>,
    keys: Vec<(Expr, bool)>, // (expression, asc)
    temp_dir: PathBuf,
    memory_budget: usize,
    merge_state: Option<MergeState>,
}

impl PhysicalSort {
    pub fn new(
        source: Box<dyn PhysicalOperator>,
        keys: Vec<(Expr, bool)>,
        temp_dir: PathBuf,
        memory_budget: usize,
    ) -> Self {
        Self {
            source,
            keys,
            temp_dir,
            memory_budget,
            merge_state: None,
        }
    }

    fn sort_buffer(&self, buffer: &mut [(Vec<DbValue>, Row)]) -> Result<(), String> {
        let mut err = None;
        buffer.sort_by(|a, b| {
            for (idx, (_, asc)) in self.keys.iter().enumerate() {
                let a_val = &a.0[idx];
                let b_val = &b.0[idx];
                match compare_values(a_val, b_val) {
                    Ok(ord) => {
                        if ord != std::cmp::Ordering::Equal {
                            return if *asc { ord } else { ord.reverse() };
                        }
                    }
                    Err(e) => {
                        err = Some(e);
                        return std::cmp::Ordering::Equal;
                    }
                }
            }
            std::cmp::Ordering::Equal
        });

        if let Some(e) = err {
            return Err(e);
        }
        Ok(())
    }

    fn flush_to_disk(&self, buffer: &[(Vec<DbValue>, Row)]) -> Result<SortedRun, String> {
        static RUN_COUNTER: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
        let run_id = RUN_COUNTER.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        let path = self
            .temp_dir
            .join(format!("sort_run_{}_{}.bin", std::process::id(), run_id));

        let file = File::create(&path)
            .map_err(|e| format!("Failed to create temp file {:?}: {}", path, e))?;
        let mut writer = BufWriter::new(file);

        bincode::serialize_into(&mut writer, &(buffer.len() as u64))
            .map_err(|e| format!("Serialization error: {}", e))?;

        for (keys, row) in buffer {
            bincode::serialize_into(&mut writer, keys)
                .map_err(|e| format!("Serialization error: {}", e))?;
            bincode::serialize_into(&mut writer, row)
                .map_err(|e| format!("Serialization error: {}", e))?;
        }

        writer
            .flush()
            .map_err(|e| format!("Failed to flush temp file: {}", e))?;

        Ok(SortedRun::new(path, buffer.len()))
    }
}

impl PhysicalOperator for PhysicalSort {
    fn next(&mut self) -> Result<Option<Row>, String> {
        if self.merge_state.is_none() {
            let source_schema = self.source.schema().clone();
            let mut buffer: Vec<(Vec<DbValue>, Row)> = Vec::new();
            let mut buffer_bytes: usize = 0;
            let mut runs: Vec<SortedRun> = Vec::new();

            while let Some(row) = self.source.next()? {
                let mut row_keys = Vec::with_capacity(self.keys.len());
                for (expr, _) in &self.keys {
                    let val = expr.eval(&row, &source_schema)?;
                    row_keys.push(val);
                }

                let size = estimate_row_size(&row_keys, &row);
                buffer_bytes += size;
                buffer.push((row_keys, row));

                if buffer_bytes >= self.memory_budget {
                    self.sort_buffer(&mut buffer)?;
                    let run = self.flush_to_disk(&buffer)?;
                    runs.push(run);
                    buffer.clear();
                    buffer_bytes = 0;
                }
            }

            if runs.is_empty() {
                self.sort_buffer(&mut buffer)?;
                self.merge_state = Some(MergeState::InMemory(
                    buffer
                        .into_iter()
                        .map(|(_, row)| row)
                        .collect::<Vec<_>>()
                        .into_iter(),
                ));
            } else {
                if !buffer.is_empty() {
                    self.sort_buffer(&mut buffer)?;
                    let run = self.flush_to_disk(&buffer)?;
                    runs.push(run);
                }
                let merger = KWayMerge::new(runs, &self.keys)?;
                self.merge_state = Some(MergeState::External(merger));
            }
        }

        match self.merge_state.as_mut().unwrap() {
            MergeState::InMemory(iter) => Ok(iter.next()),
            MergeState::External(merger) => merger.next(),
        }
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        let keys_str: Vec<String> = self
            .keys
            .iter()
            .map(|(expr, asc)| format!("{:?} {}", expr, if *asc { "ASC" } else { "DESC" }))
            .collect();
        out.push_str(&format!(
            "{}- PhysicalSort: keys={:?}\n",
            "  ".repeat(indent),
            keys_str
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 6. HashJoin Physical Operator (Semi-Blocking)
// ==========================================
pub struct PhysicalHashJoin {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    left_on: Expr,
    right_on: Expr,
    join_type: JoinType,
    schema: Schema,
    left_schema: Schema,
    right_schema: Schema,
    // Build phase hash map: DbValue representation of join key -> Right Rows
    hash_table: Option<HashMap<DbValue, Vec<Row>>>,
    // Buffer to hold joined rows from the current probe row
    join_buffer: Vec<Row>,
    join_buffer_index: usize,
}

impl PhysicalHashJoin {
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        left_on: Expr,
        right_on: Expr,
        join_type: JoinType,
        schema: Schema,
    ) -> Self {
        let left_schema = left.schema().clone();
        let right_schema = right.schema().clone();
        Self {
            left,
            right,
            left_on,
            right_on,
            join_type,
            schema,
            left_schema,
            right_schema,
            hash_table: None,
            join_buffer: Vec::new(),
            join_buffer_index: 0,
        }
    }
}

impl PhysicalOperator for PhysicalHashJoin {
    fn next(&mut self) -> Result<Option<Row>, String> {
        // If there are rows buffered from the previous probe match, yield them
        if self.join_buffer_index < self.join_buffer.len() {
            let row = self.join_buffer[self.join_buffer_index].clone();
            self.join_buffer_index += 1;
            if self.join_buffer_index >= self.join_buffer.len() {
                self.join_buffer.clear();
                self.join_buffer_index = 0;
            }
            return Ok(Some(row));
        }

        // Build phase: read all right rows into the hash table
        if self.hash_table.is_none() {
            let mut table = HashMap::new();
            while let Some(row) = self.right.next()? {
                let key_val = self.right_on.eval(&row, &self.right_schema)?;
                if key_val != DbValue::Null {
                    table.entry(key_val).or_insert_with(Vec::new).push(row);
                }
            }
            self.hash_table = Some(table);
        }

        let hash_table = self.hash_table.as_ref().unwrap();

        // Probe phase: stream left rows one by one
        while let Some(left_row) = self.left.next()? {
            let key_val = self.left_on.eval(&left_row, &self.left_schema)?;

            if key_val != DbValue::Null {
                if let Some(right_rows) = hash_table.get(&key_val) {
                    // Generate joined rows: combine left row fields + right row fields
                    for right_row in right_rows {
                        let mut merged_values = left_row.values.clone();
                        merged_values.extend(right_row.values.clone());
                        self.join_buffer.push(Row::new(merged_values));
                    }
                } else if self.join_type == JoinType::Left {
                    // Left outer join mismatch: pad right columns with NULL values
                    let mut merged_values = left_row.values.clone();
                    for _ in &self.right_schema.columns {
                        merged_values.push(DbValue::Null);
                    }
                    self.join_buffer.push(Row::new(merged_values));
                }
            } else if self.join_type == JoinType::Left {
                // Left outer join mismatch: pad right columns with NULL values
                let mut merged_values = left_row.values.clone();
                for _ in &self.right_schema.columns {
                    merged_values.push(DbValue::Null);
                }
                self.join_buffer.push(Row::new(merged_values));
            }

            if self.join_buffer_index < self.join_buffer.len() {
                let row = self.join_buffer[self.join_buffer_index].clone();
                self.join_buffer_index += 1;
                if self.join_buffer_index >= self.join_buffer.len() {
                    self.join_buffer.clear();
                    self.join_buffer_index = 0;
                }
                return Ok(Some(row));
            }
        }

        Ok(None)
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalHashJoin: type={:?}, left_on={:?}, right_on={:?}\n",
            "  ".repeat(indent),
            self.join_type,
            self.left_on,
            self.right_on
        ));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}

// ==========================================
// 6.5. CrossJoin Physical Operator (Cartesian Product)
// ==========================================
pub struct PhysicalCrossJoin {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    schema: Schema,
    // Build phase buffer: read all right rows into memory
    right_rows: Option<Vec<Row>>,
    current_left_row: Option<Row>,
    right_index: usize,
}

impl PhysicalCrossJoin {
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        schema: Schema,
    ) -> Self {
        Self {
            left,
            right,
            schema,
            right_rows: None,
            current_left_row: None,
            right_index: 0,
        }
    }
}

impl PhysicalOperator for PhysicalCrossJoin {
    fn next(&mut self) -> Result<Option<Row>, String> {
        // Build phase: read all right rows into memory
        if self.right_rows.is_none() {
            let mut rows = Vec::new();
            while let Some(row) = self.right.next()? {
                rows.push(row);
            }
            self.right_rows = Some(rows);
        }

        let right_rows = self.right_rows.as_ref().unwrap();
        if right_rows.is_empty() {
            return Ok(None);
        }

        loop {
            if self.current_left_row.is_none() {
                self.current_left_row = self.left.next()?;
                self.right_index = 0;
                if self.current_left_row.is_none() {
                    return Ok(None);
                }
            }

            let left_row = self.current_left_row.as_ref().unwrap();
            if self.right_index < right_rows.len() {
                let right_row = &right_rows[self.right_index];
                self.right_index += 1;

                let mut merged_values = left_row.values.clone();
                merged_values.extend(right_row.values.clone());
                return Ok(Some(Row::new(merged_values)));
            } else {
                self.current_left_row = None;
            }
        }
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!("{}- PhysicalCrossJoin\n", "  ".repeat(indent)));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}

// ==========================================
// 7. HashAggregate Physical Operator (Pipeline-Blocking)
// ==========================================
pub struct PhysicalHashAggregate {
    source: Box<dyn PhysicalOperator>,
    group_by: Vec<Expr>,
    aggrs: Vec<AggregateExpr>,
    schema: Schema,
    aggregated_rows: Option<std::vec::IntoIter<Row>>,
}

impl PhysicalHashAggregate {
    pub fn new(
        source: Box<dyn PhysicalOperator>,
        group_by: Vec<Expr>,
        aggrs: Vec<AggregateExpr>,
        schema: Schema,
    ) -> Self {
        Self {
            source,
            group_by,
            aggrs,
            schema,
            aggregated_rows: None,
        }
    }
}

impl PhysicalOperator for PhysicalHashAggregate {
    fn next(&mut self) -> Result<Option<Row>, String> {
        if self.aggregated_rows.is_none() {
            // Blocking phase: group and accumulate aggregates for all source rows
            let mut groups: HashMap<Vec<DbValue>, Vec<Accumulator>> = HashMap::new();

            let source_schema = self.source.schema().clone();

            while let Some(row) = self.source.next()? {
                // 1. Compute group-by values
                let mut group_vals = Vec::new();
                for expr in &self.group_by {
                    let val = expr.eval(&row, &source_schema)?;
                    group_vals.push(val);
                }

                // 2. Initialize accumulators if group is seen for the first time
                let accumulators = groups.entry(group_vals).or_insert_with(|| {
                    self.aggrs
                        .iter()
                        .map(|aggr| match aggr {
                            AggregateExpr::Count(_) => Accumulator::Count { count: 0 },
                            AggregateExpr::Sum(_) => Accumulator::Sum {
                                int_sum: None,
                                float_sum: None,
                            },
                            AggregateExpr::Min(_) => Accumulator::Min { min: None },
                            AggregateExpr::Max(_) => Accumulator::Max { max: None },
                            AggregateExpr::Avg(_) => Accumulator::Avg { sum: 0.0, count: 0 },
                        })
                        .collect()
                });

                // 3. Update accumulators with column values
                for (idx, aggr) in self.aggrs.iter().enumerate() {
                    let val = match aggr {
                        AggregateExpr::Count(expr)
                        | AggregateExpr::Sum(expr)
                        | AggregateExpr::Min(expr)
                        | AggregateExpr::Max(expr)
                        | AggregateExpr::Avg(expr) => expr.eval(&row, &source_schema)?,
                    };
                    accumulators[idx].update(&val)?;
                }
            }

            if self.group_by.is_empty() && groups.is_empty() {
                let initial_accumulators = self
                    .aggrs
                    .iter()
                    .map(|aggr| match aggr {
                        AggregateExpr::Count(_) => Accumulator::Count { count: 0 },
                        AggregateExpr::Sum(_) => Accumulator::Sum {
                            int_sum: None,
                            float_sum: None,
                        },
                        AggregateExpr::Min(_) => Accumulator::Min { min: None },
                        AggregateExpr::Max(_) => Accumulator::Max { max: None },
                        AggregateExpr::Avg(_) => Accumulator::Avg { sum: 0.0, count: 0 },
                    })
                    .collect();
                groups.insert(Vec::new(), initial_accumulators);
            }

            // 4. Construct final output rows
            let mut output_rows = Vec::new();
            for (group_vals, accumulators) in groups {
                let mut row_vals = group_vals; // starts with group-by keys
                for acc in accumulators {
                    row_vals.push(acc.finalize());
                }
                output_rows.push(Row::new(row_vals));
            }

            self.aggregated_rows = Some(output_rows.into_iter());
        }

        Ok(self.aggregated_rows.as_mut().unwrap().next())
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalHashAggregate: group_by={:?}, aggrs={:?}\n",
            "  ".repeat(indent),
            self.group_by,
            self.aggrs
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 7.5. SortedAggregate Physical Operator (Streaming)
// ==========================================
pub struct PhysicalSortedAggregate {
    source: Box<dyn PhysicalOperator>,
    group_by: Vec<Expr>,
    aggrs: Vec<AggregateExpr>,
    schema: Schema,
    active_group_keys: Option<Vec<DbValue>>,
    active_accumulators: Vec<Accumulator>,
    next_row: Option<Row>,
    source_exhausted: bool,
}

impl PhysicalSortedAggregate {
    pub fn new(
        source: Box<dyn PhysicalOperator>,
        group_by: Vec<Expr>,
        aggrs: Vec<AggregateExpr>,
        schema: Schema,
    ) -> Self {
        Self {
            source,
            group_by,
            aggrs,
            schema,
            active_group_keys: None,
            active_accumulators: Vec::new(),
            next_row: None,
            source_exhausted: false,
        }
    }
}

impl PhysicalOperator for PhysicalSortedAggregate {
    fn next(&mut self) -> Result<Option<Row>, String> {
        let source_schema = self.source.schema().clone();

        if self.next_row.is_none() && !self.source_exhausted {
            self.next_row = self.source.next()?;
            if self.next_row.is_none() {
                self.source_exhausted = true;
                if self.group_by.is_empty() && self.active_group_keys.is_none() {
                    self.active_group_keys = Some(Vec::new());
                    self.active_accumulators = self
                        .aggrs
                        .iter()
                        .map(|aggr| match aggr {
                            AggregateExpr::Count(_) => Accumulator::Count { count: 0 },
                            AggregateExpr::Sum(_) => Accumulator::Sum {
                                int_sum: None,
                                float_sum: None,
                            },
                            AggregateExpr::Min(_) => Accumulator::Min { min: None },
                            AggregateExpr::Max(_) => Accumulator::Max { max: None },
                            AggregateExpr::Avg(_) => Accumulator::Avg { sum: 0.0, count: 0 },
                        })
                        .collect();
                }
            }
        }

        loop {
            let row = match self.next_row.take() {
                Some(r) => r,
                None => {
                    if let Some(keys) = self.active_group_keys.take() {
                        let mut row_vals = keys;
                        for acc in self.active_accumulators.drain(..) {
                            row_vals.push(acc.finalize());
                        }
                        return Ok(Some(Row::new(row_vals)));
                    }
                    return Ok(None);
                }
            };

            let mut group_vals = Vec::with_capacity(self.group_by.len());
            for expr in &self.group_by {
                let val = expr.eval(&row, &source_schema)?;
                group_vals.push(val);
            }

            if let Some(active_keys) = &self.active_group_keys {
                if group_vals == *active_keys {
                    for (idx, aggr) in self.aggrs.iter().enumerate() {
                        let val = match aggr {
                            AggregateExpr::Count(expr)
                            | AggregateExpr::Sum(expr)
                            | AggregateExpr::Min(expr)
                            | AggregateExpr::Max(expr)
                            | AggregateExpr::Avg(expr) => expr.eval(&row, &source_schema)?,
                        };
                        self.active_accumulators[idx].update(&val)?;
                    }

                    self.next_row = self.source.next()?;
                    if self.next_row.is_none() {
                        self.source_exhausted = true;
                    }
                } else {
                    self.next_row = Some(row);

                    let keys = self.active_group_keys.take().unwrap();
                    let mut row_vals = keys;
                    for acc in self.active_accumulators.drain(..) {
                        row_vals.push(acc.finalize());
                    }
                    return Ok(Some(Row::new(row_vals)));
                }
            } else {
                self.active_group_keys = Some(group_vals);
                self.active_accumulators = self
                    .aggrs
                    .iter()
                    .map(|aggr| match aggr {
                        AggregateExpr::Count(_) => Accumulator::Count { count: 0 },
                        AggregateExpr::Sum(_) => Accumulator::Sum {
                            int_sum: None,
                            float_sum: None,
                        },
                        AggregateExpr::Min(_) => Accumulator::Min { min: None },
                        AggregateExpr::Max(_) => Accumulator::Max { max: None },
                        AggregateExpr::Avg(_) => Accumulator::Avg { sum: 0.0, count: 0 },
                    })
                    .collect();

                for (idx, aggr) in self.aggrs.iter().enumerate() {
                    let val = match aggr {
                        AggregateExpr::Count(expr)
                        | AggregateExpr::Sum(expr)
                        | AggregateExpr::Min(expr)
                        | AggregateExpr::Max(expr)
                        | AggregateExpr::Avg(expr) => expr.eval(&row, &source_schema)?,
                    };
                    self.active_accumulators[idx].update(&val)?;
                }

                self.next_row = self.source.next()?;
                if self.next_row.is_none() {
                    self.source_exhausted = true;
                }
            }
        }
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSortedAggregate: group_by={:?}, aggrs={:?}\n",
            "  ".repeat(indent),
            self.group_by,
            self.aggrs
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// Aggregation State Accumulators
// ==========================================
enum Accumulator {
    Count {
        count: i64,
    },
    // Track integer and floating-point running totals separately so SUM(int_col)
    // can finalize as Int when no Float input is ever observed, matching the
    // schema declared by the logical planner. We only fall back to Float if a
    // Float input appears or if the integer accumulator would overflow.
    Sum {
        int_sum: Option<i64>,
        float_sum: Option<f64>,
    },
    Min {
        min: Option<DbValue>,
    },
    Max {
        max: Option<DbValue>,
    },
    Avg {
        sum: f64,
        count: i64,
    },
}

impl Accumulator {
    fn update(&mut self, val: &DbValue) -> Result<(), String> {
        if matches!(val, DbValue::Null) {
            return Ok(()); // Ignore NULL values for all aggregates
        }
        match self {
            Accumulator::Count { count } => {
                *count += 1;
            }
            Accumulator::Sum { int_sum, float_sum } => match val {
                DbValue::Int(v) => {
                    if float_sum.is_some() {
                        // Already promoted to float; just keep accumulating in float.
                        *float_sum.as_mut().unwrap() += *v as f64;
                    } else {
                        let current = int_sum.unwrap_or(0);
                        match current.checked_add(*v) {
                            Some(new_sum) => *int_sum = Some(new_sum),
                            None => {
                                // Overflow: promote to float and continue there.
                                let promoted = current as f64 + *v as f64;
                                *int_sum = None;
                                *float_sum = Some(promoted);
                            }
                        }
                    }
                }
                DbValue::Float(v) => {
                    // First float input promotes any accumulated integers into floats.
                    let promoted = float_sum.unwrap_or(0.0) + int_sum.take().unwrap_or(0) as f64;
                    *float_sum = Some(promoted + *v);
                }
                other => {
                    return Err(format!(
                        "Cannot compute SUM on non-numeric value {:?}",
                        other
                    ));
                }
            },
            Accumulator::Min { min } => match min {
                Some(m) => {
                    let ord = compare_values(val, m)?;
                    if ord == std::cmp::Ordering::Less {
                        *min = Some(val.clone());
                    }
                }
                None => *min = Some(val.clone()),
            },
            Accumulator::Max { max } => match max {
                Some(m) => {
                    let ord = compare_values(val, m)?;
                    if ord == std::cmp::Ordering::Greater {
                        *max = Some(val.clone());
                    }
                }
                None => *max = Some(val.clone()),
            },
            Accumulator::Avg { sum, count } => {
                match val {
                    DbValue::Int(v) => *sum += *v as f64,
                    DbValue::Float(v) => *sum += *v,
                    other => {
                        return Err(format!(
                            "Cannot compute AVG on non-numeric value {:?}",
                            other
                        ));
                    }
                }
                *count += 1;
            }
        }
        Ok(())
    }

    fn finalize(&self) -> DbValue {
        match self {
            Accumulator::Count { count } => DbValue::Int(*count),
            Accumulator::Sum { int_sum, float_sum } => match (float_sum, int_sum) {
                (Some(f), _) => DbValue::Float(*f),
                (None, Some(i)) => DbValue::Int(*i),
                (None, None) => DbValue::Null,
            },
            Accumulator::Min { min } => min.clone().unwrap_or(DbValue::Null),
            Accumulator::Max { max } => max.clone().unwrap_or(DbValue::Null),
            Accumulator::Avg { sum, count } => {
                if *count == 0 {
                    DbValue::Null
                } else {
                    DbValue::Float(*sum / (*count as f64))
                }
            }
        }
    }
}

// ==========================================
// Helper Utility Functions
// ==========================================
// compare_values is imported from crate::expr::compare_values

// ==========================================
// Set Operation Physical Operator (UNION, INTERSECT, EXCEPT)
// ==========================================
pub enum SetOpState {
    Init,
    UnionDistinct {
        seen: std::collections::HashSet<Row>,
        reading_left: bool,
    },
    UnionAll {
        reading_left: bool,
    },
    Intersect {
        right_counts: std::collections::HashMap<Row, usize>,
        seen: std::collections::HashSet<Row>,
    },
    Except {
        right_counts: std::collections::HashMap<Row, usize>,
        seen: std::collections::HashSet<Row>,
    },
}

pub struct PhysicalSetOp {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    op: SetOpType,
    all: bool,
    schema: Schema,
    state: SetOpState,
}

impl PhysicalSetOp {
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        op: SetOpType,
        all: bool,
        schema: Schema,
    ) -> Self {
        Self {
            left,
            right,
            op,
            all,
            schema,
            state: SetOpState::Init,
        }
    }
}

impl PhysicalOperator for PhysicalSetOp {
    fn next(&mut self) -> Result<Option<Row>, String> {
        if matches!(self.state, SetOpState::Init) {
            match self.op {
                SetOpType::Union => {
                    if self.all {
                        self.state = SetOpState::UnionAll { reading_left: true };
                    } else {
                        self.state = SetOpState::UnionDistinct {
                            seen: std::collections::HashSet::new(),
                            reading_left: true,
                        };
                    }
                }
                SetOpType::Intersect => {
                    let mut right_counts = std::collections::HashMap::new();
                    while let Some(row) = self.right.next()? {
                        *right_counts.entry(row).or_insert(0) += 1;
                    }
                    self.state = SetOpState::Intersect {
                        right_counts,
                        seen: std::collections::HashSet::new(),
                    };
                }
                SetOpType::Except => {
                    let mut right_counts = std::collections::HashMap::new();
                    while let Some(row) = self.right.next()? {
                        *right_counts.entry(row).or_insert(0) += 1;
                    }
                    self.state = SetOpState::Except {
                        right_counts,
                        seen: std::collections::HashSet::new(),
                    };
                }
            }
        }

        match &mut self.state {
            SetOpState::UnionAll { reading_left } => {
                if *reading_left {
                    if let Some(row) = self.left.next()? {
                        return Ok(Some(row));
                    }
                    *reading_left = false;
                }
                self.right.next()
            }
            SetOpState::UnionDistinct { seen, reading_left } => {
                if *reading_left {
                    while let Some(row) = self.left.next()? {
                        if seen.insert(row.clone()) {
                            return Ok(Some(row));
                        }
                    }
                    *reading_left = false;
                }
                while let Some(row) = self.right.next()? {
                    if seen.insert(row.clone()) {
                        return Ok(Some(row));
                    }
                }
                Ok(None)
            }
            SetOpState::Intersect { right_counts, seen } => {
                while let Some(row) = self.left.next()? {
                    if self.all {
                        if let Some(count) = right_counts.get_mut(&row).filter(|c| **c > 0) {
                            *count -= 1;
                            return Ok(Some(row));
                        }
                    } else if right_counts.contains_key(&row) && seen.insert(row.clone()) {
                        return Ok(Some(row));
                    }
                }
                Ok(None)
            }
            SetOpState::Except { right_counts, seen } => {
                while let Some(row) = self.left.next()? {
                    if self.all {
                        if let Some(count) = right_counts.get_mut(&row).filter(|c| **c > 0) {
                            *count -= 1;
                            continue;
                        }
                        return Ok(Some(row));
                    } else if !right_counts.contains_key(&row) && seen.insert(row.clone()) {
                        return Ok(Some(row));
                    }
                }
                Ok(None)
            }
            SetOpState::Init => unreachable!(),
        }
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSetOp: op={:?}, all={}\n",
            "  ".repeat(indent),
            self.op,
            self.all
        ));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}

// ==========================================
// 9. Distinct Physical Operator (Streaming)
// ==========================================
pub struct PhysicalDistinct {
    source: Box<dyn PhysicalOperator>,
    seen: HashSet<Row>,
}

impl PhysicalDistinct {
    pub fn new(source: Box<dyn PhysicalOperator>) -> Self {
        Self {
            source,
            seen: HashSet::new(),
        }
    }
}

impl PhysicalOperator for PhysicalDistinct {
    fn next(&mut self) -> Result<Option<Row>, String> {
        while let Some(row) = self.source.next()? {
            if self.seen.insert(row.clone()) {
                return Ok(Some(row));
            }
        }
        Ok(None)
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!("{}- PhysicalDistinct\n", "  ".repeat(indent)));
        self.source.explain(indent + 1, out);
    }
}
