use crate::engine::resolve_count_expr;
use crate::expr::{Expr, compare_values};
use crate::logical::{AggregateExpr, FtsQuery, JoinType, PlanKey, SetOpType};
use crate::spill::{self, KWayMerge, Run};
use dtdb_relational::{Row, Schema, Transaction};
use dtdb_storage::DbValue;
use rust_decimal::prelude::{FromPrimitive, ToPrimitive};
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

/// PhysicalOperator defines the Volcano Iterator interface for query execution.
pub trait PhysicalOperator: Send + Sync {
    /// Spawns/opens a stateful execution iterator for this operator using the given transaction and parameters.
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String>;

    /// Returns the output Schema generated by this operator.
    fn schema(&self) -> &Schema;

    /// Formats the operator tree recursively for explanation.
    fn explain(&self, indent: usize, out: &mut String);
}

// ==========================================
// 1. SeqScan Physical Operator
// ==========================================
pub struct PhysicalSeqScan {
    schema: Schema,
    table_name: String,
    columns: Option<Vec<String>>,
    range: Option<(PlanKey, PlanKey)>,
}

impl PhysicalSeqScan {
    pub fn new(
        schema: Schema,
        table_name: String,
        columns: Option<Vec<String>>,
        range: Option<(PlanKey, PlanKey)>,
    ) -> Self {
        Self {
            schema,
            table_name,
            columns,
            range,
        }
    }
}

impl PhysicalOperator for PhysicalSeqScan {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let (start, end) = match &self.range {
            Some((start_key, end_key)) => (start_key.resolve(params)?, end_key.resolve(params)?),
            None => self
                .schema
                .primary_key_bounds()
                .map_err(|e| e.to_string())?,
        };

        let iter = tx
            .scan_iter(&self.table_name, &start, &end, self.columns.as_deref())
            .map_err(|e| e.to_string())?;

        struct SeqScanIterator {
            iter: dtdb_relational::TransactionScanIterator,
        }

        impl Iterator for SeqScanIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                match self.iter.next() {
                    Ok(Some(row)) => Some(Ok(row)),
                    Ok(None) => None,
                    Err(e) => Some(Err(e.to_string())),
                }
            }
        }

        Ok(Box::new(SeqScanIterator { iter }))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSeqScan: schema={:?}\n",
            "  ".repeat(indent),
            self.schema
        ));
    }
}

// ==========================================
// 1.5. IndexScan Physical Operator
// ==========================================
pub struct PhysicalIndexScan {
    schema: Schema,
    table_name: String,
    index_name: String,
    range: Option<(PlanKey, PlanKey)>,
    columns: Option<Vec<String>>,
}

impl PhysicalIndexScan {
    pub fn new(
        schema: Schema,
        table_name: String,
        index_name: String,
        range: Option<(PlanKey, PlanKey)>,
        columns: Option<Vec<String>>,
    ) -> Self {
        Self {
            schema,
            table_name,
            index_name,
            range,
            columns,
        }
    }
}

impl PhysicalOperator for PhysicalIndexScan {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let (start, end) = match &self.range {
            Some((start_key, end_key)) => (start_key.resolve(params)?, end_key.resolve(params)?),
            None => {
                let idx_def = self
                    .schema
                    .indexes
                    .iter()
                    .find(|idx| idx.name == self.index_name)
                    .ok_or_else(|| {
                        format!(
                            "Index '{}' not found in schema during execution",
                            self.index_name
                        )
                    })?;
                let col_name = idx_def
                    .columns
                    .first()
                    .ok_or_else(|| format!("Index '{}' defines no columns", self.index_name))?;
                let col = self
                    .schema
                    .columns
                    .iter()
                    .find(|c| c.matches_name(col_name))
                    .ok_or_else(|| format!("Indexed column '{}' not found in schema", col_name))?;
                col.data_type.key_bounds()
            }
        };

        let rows = tx
            .index_scan(
                &self.table_name,
                &self.index_name,
                &start,
                &end,
                self.columns.as_deref(),
            )
            .map_err(|e| e.to_string())?;

        Ok(Box::new(rows.into_iter().map(Ok)))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalIndexScan: schema={:?}\n",
            "  ".repeat(indent),
            self.schema
        ));
    }
}

// ==========================================
// 1.7. FullTextScan Physical Operator
// ==========================================
pub struct PhysicalFullTextScan {
    schema: Schema,
    table_name: String,
    index_name: String,
    query: FtsQuery,
    columns: Option<Vec<String>>,
}

impl PhysicalFullTextScan {
    pub fn new(
        schema: Schema,
        table_name: String,
        index_name: String,
        query: FtsQuery,
        columns: Option<Vec<String>>,
    ) -> Self {
        Self {
            schema,
            table_name,
            index_name,
            query,
            columns,
        }
    }
}

impl PhysicalOperator for PhysicalFullTextScan {
    fn execute(
        &self,
        tx: &Transaction,
        _params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let rows = match &self.query {
            FtsQuery::Match(query_str) => tx
                .fulltext_scan(
                    &self.table_name,
                    &self.index_name,
                    query_str,
                    self.columns.as_deref(),
                )
                .map_err(|e| e.to_string())?,
            FtsQuery::AllTokens(tokens) => tx
                .token_intersection_scan(
                    &self.table_name,
                    &self.index_name,
                    tokens,
                    self.columns.as_deref(),
                )
                .map_err(|e| e.to_string())?,
        };

        Ok(Box::new(rows.into_iter().map(Ok)))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        let query_label = match &self.query {
            FtsQuery::Match(query_str) => query_str.clone(),
            FtsQuery::AllTokens(tokens) => format!("AllTokens({tokens:?})"),
        };
        out.push_str(&format!(
            "{}- PhysicalFullTextScan: query={:?}, schema={:?}\n",
            "  ".repeat(indent),
            query_label,
            self.schema
        ));
    }
}

// ==========================================
// 2. Filter Physical Operator
// ==========================================
pub struct PhysicalFilter {
    source: Box<dyn PhysicalOperator>,
    predicate: Expr,
}

impl PhysicalFilter {
    pub fn new(source: Box<dyn PhysicalOperator>, predicate: Expr) -> Self {
        Self { source, predicate }
    }
}

impl PhysicalOperator for PhysicalFilter {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let child_iter = self.source.execute(tx, params)?;
        let child_schema = self.source.schema().clone();
        let predicate = self.predicate.clone();

        struct FilterIterator {
            iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            predicate: Expr,
            schema: Schema,
        }

        impl Iterator for FilterIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                loop {
                    match self.iter.next() {
                        Some(Ok(row)) => {
                            match self.predicate.eval(&row, &self.schema) {
                                Ok(res) => match res {
                                    DbValue::Bool(b) if b => return Some(Ok(row)),
                                    DbValue::Int(v) if v != 0 => return Some(Ok(row)),
                                    _ => {} // Skip row
                                },
                                Err(e) => return Some(Err(e)),
                            }
                        }
                        Some(Err(e)) => return Some(Err(e)),
                        None => return None,
                    }
                }
            }
        }

        Ok(Box::new(FilterIterator {
            iter: child_iter,
            predicate,
            schema: child_schema,
        }))
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalFilter: predicate={:?}\n",
            "  ".repeat(indent),
            self.predicate
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 3. Projection Physical Operator
// ==========================================
pub struct PhysicalProjection {
    source: Box<dyn PhysicalOperator>,
    expressions: Vec<Expr>,
    schema: Schema,
}

impl PhysicalProjection {
    pub fn new(source: Box<dyn PhysicalOperator>, expressions: Vec<Expr>, schema: Schema) -> Self {
        Self {
            source,
            expressions,
            schema,
        }
    }
}

impl PhysicalOperator for PhysicalProjection {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let child_iter = self.source.execute(tx, params)?;
        let child_schema = self.source.schema().clone();
        let expressions = self.expressions.clone();

        struct ProjectionIterator {
            iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            expressions: Vec<Expr>,
            schema: Schema,
        }

        impl Iterator for ProjectionIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                match self.iter.next() {
                    Some(Ok(row)) => {
                        let mut projected_vals = Vec::new();
                        for expr in &self.expressions {
                            match expr.eval(&row, &self.schema) {
                                Ok(val) => projected_vals.push(val),
                                Err(e) => return Some(Err(e)),
                            }
                        }
                        Some(Ok(Row::new(projected_vals)))
                    }
                    Some(Err(e)) => Some(Err(e)),
                    None => None,
                }
            }
        }

        Ok(Box::new(ProjectionIterator {
            iter: child_iter,
            expressions,
            schema: child_schema,
        }))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalProjection: expressions={:?}\n",
            "  ".repeat(indent),
            self.expressions
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 4. Limit Physical Operator
// ==========================================

pub struct PhysicalLimit {
    source: Box<dyn PhysicalOperator>,
    limit: Option<Expr>,
    offset: Option<Expr>,
}

impl PhysicalLimit {
    pub fn new(
        source: Box<dyn PhysicalOperator>,
        limit: Option<Expr>,
        offset: Option<Expr>,
    ) -> Self {
        Self {
            source,
            limit,
            offset,
        }
    }
}

impl PhysicalOperator for PhysicalLimit {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let child_iter = self.source.execute(tx, params)?;
        let limit = self
            .limit
            .as_ref()
            .map(|e| resolve_count_expr(e, params))
            .transpose()?;
        let offset = self
            .offset
            .as_ref()
            .map(|e| resolve_count_expr(e, params))
            .transpose()?
            .unwrap_or(0);

        struct LimitIterator {
            iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            limit: Option<usize>,
            offset: usize,
            skipped: usize,
            returned: usize,
        }

        impl Iterator for LimitIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                // Skip offset rows first
                while self.skipped < self.offset {
                    match self.iter.next() {
                        Some(Ok(_)) => {
                            self.skipped += 1;
                        }
                        Some(Err(e)) => return Some(Err(e)),
                        None => return None,
                    }
                }

                if let Some(lim) = self.limit
                    && self.returned >= lim
                {
                    return None;
                }

                match self.iter.next() {
                    Some(Ok(row)) => {
                        self.returned += 1;
                        Some(Ok(row))
                    }
                    Some(Err(e)) => Some(Err(e)),
                    None => None,
                }
            }
        }

        Ok(Box::new(LimitIterator {
            iter: child_iter,
            limit,
            offset,
            skipped: 0,
            returned: 0,
        }))
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        let limit_str = match &self.limit {
            Some(l) => format!("{:?}", l),
            None => "none".to_string(),
        };
        let offset_str = match &self.offset {
            Some(o) => format!("{:?}", o),
            None => "0".to_string(),
        };
        out.push_str(&format!(
            "{}- PhysicalLimit: limit={}, offset={}\n",
            "  ".repeat(indent),
            limit_str,
            offset_str
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 5. Sort Physical Operator (Pipeline-Blocking)
// ==========================================
enum MergeState {
    InMemory(std::vec::IntoIter<Row>),
    External(KWayMerge<Row>),
}

pub struct PhysicalSort {
    source: Box<dyn PhysicalOperator>,
    keys: Vec<(Expr, bool)>, // (expression, asc)
    temp_dir: PathBuf,
    memory_budget: usize,
}

impl PhysicalSort {
    pub fn new(
        source: Box<dyn PhysicalOperator>,
        keys: Vec<(Expr, bool)>,
        temp_dir: PathBuf,
        memory_budget: usize,
    ) -> Self {
        Self {
            source,
            keys,
            temp_dir,
            memory_budget,
        }
    }

    fn directions(&self) -> Vec<bool> {
        self.keys.iter().map(|(_, asc)| *asc).collect()
    }
}

impl PhysicalOperator for PhysicalSort {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let child_iter = self.source.execute(tx, params)?;
        let child_schema = self.source.schema().clone();
        let directions = self.directions();
        let keys = self.keys.clone();
        let temp_dir = self.temp_dir.clone();
        let memory_budget = self.memory_budget;

        struct SortIterator {
            iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            schema: Schema,
            keys: Vec<(Expr, bool)>,
            directions: Vec<bool>,
            temp_dir: PathBuf,
            memory_budget: usize,
            merge_state: Option<MergeState>,
        }

        impl Iterator for SortIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                if self.merge_state.is_none() {
                    let mut buffer: Vec<(Vec<DbValue>, Row)> = Vec::new();
                    let mut buffer_bytes: usize = 0;
                    let mut runs: Vec<Run<Row>> = Vec::new();

                    for row_res in self.iter.by_ref() {
                        let row = match row_res {
                            Ok(r) => r,
                            Err(e) => return Some(Err(e)),
                        };

                        let mut row_keys = Vec::with_capacity(self.keys.len());
                        for (expr, _) in &self.keys {
                            match expr.eval(&row, &self.schema) {
                                Ok(val) => row_keys.push(val),
                                Err(e) => return Some(Err(e)),
                            }
                        }

                        buffer_bytes += spill::estimate_row_size(&row_keys, &row.values);
                        buffer.push((row_keys, row));

                        if buffer_bytes >= self.memory_budget {
                            spill::sort_entries(&mut buffer, &self.directions);
                            match spill::write_run(&self.temp_dir, "sort_run", &buffer) {
                                Ok(run) => runs.push(run),
                                Err(e) => return Some(Err(e)),
                            }
                            buffer.clear();
                            buffer_bytes = 0;
                        }
                    }

                    if runs.is_empty() {
                        spill::sort_entries(&mut buffer, &self.directions);
                        self.merge_state = Some(MergeState::InMemory(
                            buffer
                                .into_iter()
                                .map(|(_, row)| row)
                                .collect::<Vec<_>>()
                                .into_iter(),
                        ));
                    } else {
                        if !buffer.is_empty() {
                            spill::sort_entries(&mut buffer, &self.directions);
                            match spill::write_run(&self.temp_dir, "sort_run", &buffer) {
                                Ok(run) => runs.push(run),
                                Err(e) => return Some(Err(e)),
                            }
                        }
                        match KWayMerge::new(
                            runs,
                            self.directions.clone(),
                            &self.temp_dir,
                            "sort_run",
                        ) {
                            Ok(merger) => self.merge_state = Some(MergeState::External(merger)),
                            Err(e) => return Some(Err(e)),
                        }
                    }
                }

                match self.merge_state.as_mut().unwrap() {
                    MergeState::InMemory(iter) => iter.next().map(Ok),
                    MergeState::External(merger) => match merger.next() {
                        Ok(Some((_, row))) => Some(Ok(row)),
                        Ok(None) => None,
                        Err(e) => Some(Err(e)),
                    },
                }
            }
        }

        Ok(Box::new(SortIterator {
            iter: child_iter,
            schema: child_schema,
            keys,
            directions,
            temp_dir,
            memory_budget,
            merge_state: None,
        }))
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        let keys_str: Vec<String> = self
            .keys
            .iter()
            .map(|(expr, asc)| format!("{:?} {}", expr, if *asc { "ASC" } else { "DESC" }))
            .collect();
        out.push_str(&format!(
            "{}- PhysicalSort: keys={:?}\n",
            "  ".repeat(indent),
            keys_str
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 5.5. Top-N Physical Operator (Sort + Limit fusion)
// ==========================================
/// One retained row plus its evaluated sort key. `Ord` is the *natural* sort
/// order (per `directions`), so a `BinaryHeap<TopNEntry>` is a max-heap whose top
/// is the worst retained row — the one evicted when a better row arrives.
struct TopNEntry {
    keys: Vec<DbValue>,
    row: Row,
    directions: std::sync::Arc<Vec<bool>>,
}

impl Ord for TopNEntry {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        spill::compare_keys(&self.keys, &other.keys, &self.directions)
    }
}

impl PartialOrd for TopNEntry {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl PartialEq for TopNEntry {
    fn eq(&self, other: &Self) -> bool {
        self.cmp(other) == std::cmp::Ordering::Equal
    }
}

impl Eq for TopNEntry {}

/// Bounded top-k: where [`PhysicalSort`] materializes and sorts its entire input
/// (spilling to disk) only for an outer `LIMIT` to discard all but the first
/// rows, `PhysicalTopN` retains just the `k` best rows in a bounded max-heap of
/// capacity `k` — turning an O(n log n) external sort into an O(n log k) in-memory
/// pass with no spilling. It is produced by fusing a `LIMIT` with an
/// immediately-underlying `ORDER BY` during physical compilation, with
/// `k = OFFSET + LIMIT`; the outer [`PhysicalLimit`] still applies the actual
/// offset/limit slice over the rows emitted here (in sorted order).
///
/// Only used when `k` is small enough to stay within the memory budget — deeper
/// limits keep the spilling `PhysicalSort` + `PhysicalLimit` path instead.
pub struct PhysicalTopN {
    source: Box<dyn PhysicalOperator>,
    keys: Vec<(Expr, bool)>, // (expression, asc)
    k: usize,
}

impl PhysicalTopN {
    pub fn new(source: Box<dyn PhysicalOperator>, keys: Vec<(Expr, bool)>, k: usize) -> Self {
        Self { source, keys, k }
    }

    fn directions(&self) -> std::sync::Arc<Vec<bool>> {
        std::sync::Arc::new(self.keys.iter().map(|(_, asc)| *asc).collect())
    }
}

impl PhysicalOperator for PhysicalTopN {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let source_iter = self.source.execute(tx, params)?;
        let source_schema = self.source.schema().clone();
        let directions = self.directions();
        let k = self.k;
        let mut keys = self.keys.clone();
        for (expr, _) in &mut keys {
            expr.substitute_params(params)?;
        }

        struct TopNIterator {
            source_iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            keys: Vec<(Expr, bool)>,
            source_schema: Schema,
            directions: std::sync::Arc<Vec<bool>>,
            k: usize,
            output: Option<std::vec::IntoIter<Row>>,
        }

        impl Iterator for TopNIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                if self.output.is_none() {
                    let mut heap: std::collections::BinaryHeap<TopNEntry> =
                        std::collections::BinaryHeap::with_capacity(self.k);

                    // k == 0 retains nothing; skip draining the source entirely.
                    while self.k > 0 {
                        let row_res = match self.source_iter.next() {
                            Some(Ok(r)) => r,
                            Some(Err(e)) => return Some(Err(e)),
                            None => break,
                        };
                        let mut keys = Vec::with_capacity(self.keys.len());
                        for (expr, _) in &self.keys {
                            match expr.eval(&row_res, &self.source_schema) {
                                Ok(val) => keys.push(val),
                                Err(e) => return Some(Err(e)),
                            }
                        }
                        let entry = TopNEntry {
                            keys,
                            row: row_res,
                            directions: std::sync::Arc::clone(&self.directions),
                        };

                        if heap.len() < self.k {
                            heap.push(entry);
                        } else if let Some(mut worst) = heap.peek_mut() {
                            // Replace the worst retained row only if this one is better,
                            // re-sifting once on drop of the `PeekMut` guard.
                            if entry < *worst {
                                *worst = entry;
                            }
                        }
                    }

                    // Popping a max-heap yields worst-to-best; reverse for ascending order.
                    let mut sorted: Vec<Row> = Vec::with_capacity(heap.len());
                    while let Some(entry) = heap.pop() {
                        sorted.push(entry.row);
                    }
                    sorted.reverse();
                    self.output = Some(sorted.into_iter());
                }

                self.output.as_mut().unwrap().next().map(Ok)
            }
        }

        Ok(Box::new(TopNIterator {
            source_iter,
            keys,
            source_schema,
            directions,
            k,
            output: None,
        }))
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        let keys_str: Vec<String> = self
            .keys
            .iter()
            .map(|(expr, asc)| format!("{:?} {}", expr, if *asc { "ASC" } else { "DESC" }))
            .collect();
        out.push_str(&format!(
            "{}- PhysicalTopN: k={}, keys={:?}\n",
            "  ".repeat(indent),
            self.k,
            keys_str
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 6. SortMergeJoin Physical Operator (Bounded-memory)
// ==========================================
/// A sorted stream of `(key, row)` pairs keyed on a single join expression, used as
/// one side of the sort-merge join. Memory is bounded by spilling sorted runs of the
/// input to disk and k-way merging them, exactly like `PhysicalSort`.
struct JoinSortedStream {
    inner: JoinStreamInner,
    head: Option<(Vec<DbValue>, Row)>,
}

enum JoinStreamInner {
    InMemory(std::vec::IntoIter<(Vec<DbValue>, Row)>),
    External(KWayMerge<Row>),
}

impl JoinSortedStream {
    /// Drains `source`, evaluating `key_expr` per row, and returns a stream that yields
    /// `(key, row)` pairs in ascending key order.
    fn build(
        source: &mut dyn Iterator<Item = Result<Row, String>>,
        source_schema: &Schema,
        key_expr: &Expr,
        temp_dir: &Path,
        memory_budget: usize,
    ) -> Result<Self, String> {
        let directions = vec![true];
        let mut buffer: Vec<(Vec<DbValue>, Row)> = Vec::new();
        let mut buffer_bytes: usize = 0;
        let mut runs: Vec<Run<Row>> = Vec::new();

        for row_res in source {
            let row = row_res?;
            let key = vec![key_expr.eval(&row, source_schema)?];
            buffer_bytes += spill::estimate_row_size(&key, &row.values);
            buffer.push((key, row));
            if buffer_bytes >= memory_budget {
                spill::sort_entries(&mut buffer, &directions);
                runs.push(spill::write_run(temp_dir, "join_run", &buffer)?);
                buffer.clear();
                buffer_bytes = 0;
            }
        }

        let inner = if runs.is_empty() {
            spill::sort_entries(&mut buffer, &directions);
            JoinStreamInner::InMemory(buffer.into_iter())
        } else {
            if !buffer.is_empty() {
                spill::sort_entries(&mut buffer, &directions);
                runs.push(spill::write_run(temp_dir, "join_run", &buffer)?);
            }
            JoinStreamInner::External(KWayMerge::new(runs, directions, temp_dir, "join_run")?)
        };

        let mut stream = Self { inner, head: None };
        stream.advance()?;
        Ok(stream)
    }

    fn advance(&mut self) -> Result<(), String> {
        self.head = match &mut self.inner {
            JoinStreamInner::InMemory(iter) => iter.next(),
            JoinStreamInner::External(merger) => merger.next()?,
        };
        Ok(())
    }

    fn peek_key(&self) -> Option<&Vec<DbValue>> {
        self.head.as_ref().map(|(k, _)| k)
    }

    /// Consumes and returns every row at the head whose key equals `key`, advancing
    /// past them. Equal keys are adjacent after the sort, so this collects a full group.
    fn take_group(&mut self, key: &[DbValue]) -> Result<Vec<Row>, String> {
        let mut group = Vec::new();
        while let Some((k, _)) = self.head.as_ref() {
            if compare_rows(k, key) == std::cmp::Ordering::Equal {
                let (_, row) = self.head.take().unwrap();
                group.push(row);
                self.advance()?;
            } else {
                break;
            }
        }
        Ok(group)
    }
}

/// Pads a left row with NULLs for every right column (left-outer non-match).
fn pad_left_row(left_row: &Row, right_cols: usize) -> Row {
    let mut merged = left_row.values.clone();
    merged.extend(std::iter::repeat_n(DbValue::Null, right_cols));
    Row::new(merged)
}

/// Equi-join via sort-merge: both inputs are externally sorted on their join key, then
/// merged by walking the two sorted streams in lockstep. Memory is bounded — only a
/// single matching key-group is buffered at a time (vs. the entire right side before).
/// Supports Inner and Left-outer joins. NULL keys never match (matching SQL semantics).
pub struct PhysicalSortMergeJoin {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    left_on: Expr,
    right_on: Expr,
    join_type: JoinType,
    schema: Schema,
    temp_dir: PathBuf,
    memory_budget: usize,
}

impl PhysicalSortMergeJoin {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        left_on: Expr,
        right_on: Expr,
        join_type: JoinType,
        schema: Schema,
        temp_dir: PathBuf,
        memory_budget: usize,
    ) -> Self {
        Self {
            left,
            right,
            left_on,
            right_on,
            join_type,
            schema,
            temp_dir,
            memory_budget,
        }
    }
}

impl PhysicalOperator for PhysicalSortMergeJoin {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let left_iter = self.left.execute(tx, params)?;
        let right_iter = self.right.execute(tx, params)?;
        let left_schema = self.left.schema().clone();
        let right_schema = self.right.schema().clone();
        let right_cols = right_schema.columns.len();

        let mut left_on = self.left_on.clone();
        left_on.substitute_params(params)?;
        let mut right_on = self.right_on.clone();
        right_on.substitute_params(params)?;

        struct SortMergeJoinIterator {
            left_source: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            right_source: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            left_schema: Schema,
            right_schema: Schema,
            left_on: Expr,
            right_on: Expr,
            join_type: JoinType,
            right_cols: usize,
            temp_dir: PathBuf,
            memory_budget: usize,
            streams: Option<(JoinSortedStream, JoinSortedStream)>,
            pending: std::collections::VecDeque<Row>,
        }

        impl Iterator for SortMergeJoinIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                if self.streams.is_none() {
                    let left = match JoinSortedStream::build(
                        &mut *self.left_source,
                        &self.left_schema,
                        &self.left_on,
                        &self.temp_dir,
                        self.memory_budget,
                    ) {
                        Ok(l) => l,
                        Err(e) => return Some(Err(e)),
                    };
                    let right = match JoinSortedStream::build(
                        &mut *self.right_source,
                        &self.right_schema,
                        &self.right_on,
                        &self.temp_dir,
                        self.memory_budget,
                    ) {
                        Ok(r) => r,
                        Err(e) => return Some(Err(e)),
                    };
                    self.streams = Some((left, right));
                }

                let is_left = self.join_type == JoinType::Left;
                let right_cols = self.right_cols;

                loop {
                    if let Some(row) = self.pending.pop_front() {
                        return Some(Ok(row));
                    }

                    let mut emits: Vec<Row> = Vec::new();
                    {
                        let (left, right) = self.streams.as_mut().unwrap();
                        let lkey = match left.peek_key() {
                            Some(k) => k.clone(),
                            None => return None,
                        };

                        // NULL keys never join; left-outer still emits the padded left row.
                        if lkey[0] == DbValue::Null {
                            let left_group = match left.take_group(&lkey) {
                                Ok(g) => g,
                                Err(e) => return Some(Err(e)),
                            };
                            if is_left {
                                emits
                                    .extend(left_group.iter().map(|r| pad_left_row(r, right_cols)));
                            }
                        } else {
                            match right.peek_key().cloned() {
                                None => {
                                    // Right exhausted: remaining left rows are unmatched.
                                    let left_group = match left.take_group(&lkey) {
                                        Ok(g) => g,
                                        Err(e) => return Some(Err(e)),
                                    };
                                    if is_left {
                                        emits.extend(
                                            left_group.iter().map(|r| pad_left_row(r, right_cols)),
                                        );
                                    }
                                }
                                Some(rkey) => match compare_rows(&lkey, &rkey) {
                                    std::cmp::Ordering::Less => {
                                        // Left key has no match on the right.
                                        let left_group = match left.take_group(&lkey) {
                                            Ok(g) => g,
                                            Err(e) => return Some(Err(e)),
                                        };
                                        if is_left {
                                            emits.extend(
                                                left_group
                                                    .iter()
                                                    .map(|r| pad_left_row(r, right_cols)),
                                            );
                                        }
                                    }
                                    std::cmp::Ordering::Greater => {
                                        // Right key has no match on the left; discard the group.
                                        if let Err(e) = right.take_group(&rkey) {
                                            return Some(Err(e));
                                        }
                                    }
                                    std::cmp::Ordering::Equal => {
                                        // Matched key: emit the cross product of the two groups.
                                        let right_group = match right.take_group(&rkey) {
                                            Ok(g) => g,
                                            Err(e) => return Some(Err(e)),
                                        };
                                        let left_group = match left.take_group(&lkey) {
                                            Ok(g) => g,
                                            Err(e) => return Some(Err(e)),
                                        };
                                        for left_row in &left_group {
                                            for right_row in &right_group {
                                                let mut merged = left_row.values.clone();
                                                merged.extend(right_row.values.clone());
                                                emits.push(Row::new(merged));
                                            }
                                        }
                                    }
                                },
                            }
                        }
                    }

                    self.pending.extend(emits);
                }
            }
        }

        Ok(Box::new(SortMergeJoinIterator {
            left_source: left_iter,
            right_source: right_iter,
            left_schema,
            right_schema,
            left_on,
            right_on,
            join_type: self.join_type,
            right_cols,
            temp_dir: self.temp_dir.clone(),
            memory_budget: self.memory_budget,
            streams: None,
            pending: std::collections::VecDeque::new(),
        }))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSortMergeJoin: type={:?}, left_on={:?}, right_on={:?}\n",
            "  ".repeat(indent),
            self.join_type,
            self.left_on,
            self.right_on
        ));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}

// ==========================================
// 6.5. CrossJoin Physical Operator (Cartesian Product)
// ==========================================
pub struct PhysicalCrossJoin {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    schema: Schema,
}

impl PhysicalCrossJoin {
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        schema: Schema,
    ) -> Self {
        Self {
            left,
            right,
            schema,
        }
    }
}

impl PhysicalOperator for PhysicalCrossJoin {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let left_iter = self.left.execute(tx, params)?;
        let right_iter = self.right.execute(tx, params)?;

        struct CrossJoinIterator {
            left_iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            right_iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            right_rows: Option<Vec<Row>>,
            current_left_row: Option<Row>,
            right_index: usize,
        }

        impl Iterator for CrossJoinIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                // Build phase: read all right rows into memory
                if self.right_rows.is_none() {
                    let mut rows = Vec::new();
                    for row_res in &mut self.right_iter {
                        match row_res {
                            Ok(row) => rows.push(row),
                            Err(e) => return Some(Err(e)),
                        }
                    }
                    self.right_rows = Some(rows);
                }

                let right_rows = self.right_rows.as_ref().unwrap();
                if right_rows.is_empty() {
                    return None;
                }

                loop {
                    if self.current_left_row.is_none() {
                        match self.left_iter.next() {
                            Some(Ok(row)) => {
                                self.current_left_row = Some(row);
                                self.right_index = 0;
                            }
                            Some(Err(e)) => return Some(Err(e)),
                            None => return None,
                        }
                    }

                    let left_row = self.current_left_row.as_ref().unwrap();
                    if self.right_index < right_rows.len() {
                        let right_row = &right_rows[self.right_index];
                        self.right_index += 1;

                        let mut merged_values = left_row.values.clone();
                        merged_values.extend(right_row.values.clone());
                        return Some(Ok(Row::new(merged_values)));
                    } else {
                        self.current_left_row = None;
                    }
                }
            }
        }

        Ok(Box::new(CrossJoinIterator {
            left_iter,
            right_iter,
            right_rows: None,
            current_left_row: None,
            right_index: 0,
        }))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!("{}- PhysicalCrossJoin\n", "  ".repeat(indent)));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}

// ==========================================
// 7. HashAggregate Physical Operator (Pipeline-Blocking)
// ==========================================
pub struct PhysicalHashAggregate {
    source: Box<dyn PhysicalOperator>,
    group_by: Vec<Expr>,
    aggrs: Vec<AggregateExpr>,
    schema: Schema,
    temp_dir: PathBuf,
    memory_budget: usize,
}

/// Output state of a hash aggregate once its build phase has run: either all groups
/// fit in memory, or partial groups were spilled and are streamed back via merge.
enum AggOutput {
    InMemory(std::vec::IntoIter<Row>),
    Merge(AggMerge),
}

/// Streams finalized rows out of spilled partial-aggregate runs, combining the
/// partial accumulators of equal group keys (which are adjacent after merge).
struct AggMerge {
    merger: KWayMerge<Vec<Accumulator>>,
    current: Option<(Vec<DbValue>, Vec<Accumulator>)>,
}

impl AggMerge {
    fn next(&mut self) -> Result<Option<Row>, String> {
        loop {
            match self.merger.next()? {
                Some((key, accs)) => match &mut self.current {
                    Some((cur_key, cur_accs)) if *cur_key == key => {
                        for (acc, partial) in cur_accs.iter_mut().zip(accs) {
                            acc.merge(partial)?;
                        }
                    }
                    _ => {
                        if let Some((k, a)) = self.current.replace((key, accs)) {
                            return Ok(Some(finalize_group(k, a)?));
                        }
                    }
                },
                None => {
                    return match self.current.take() {
                        Some((k, a)) => Ok(Some(finalize_group(k, a)?)),
                        None => Ok(None),
                    };
                }
            }
        }
    }
}

impl PhysicalHashAggregate {
    pub fn new(
        source: Box<dyn PhysicalOperator>,
        group_by: Vec<Expr>,
        aggrs: Vec<AggregateExpr>,
        schema: Schema,
        temp_dir: PathBuf,
        memory_budget: usize,
    ) -> Self {
        Self {
            source,
            group_by,
            aggrs,
            schema,
            temp_dir,
            memory_budget,
        }
    }
}

impl PhysicalOperator for PhysicalHashAggregate {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let source_iter = self.source.execute(tx, params)?;
        let source_schema = self.source.schema().clone();

        let mut group_by = self.group_by.clone();
        for expr in &mut group_by {
            expr.substitute_params(params)?;
        }
        let mut aggrs = self.aggrs.clone();
        for aggr in &mut aggrs {
            match aggr {
                AggregateExpr::Count { expr, .. }
                | AggregateExpr::Sum { expr, .. }
                | AggregateExpr::Min { expr, .. }
                | AggregateExpr::Max { expr, .. }
                | AggregateExpr::Avg { expr, .. } => {
                    expr.substitute_params(params)?;
                }
            }
        }

        struct HashAggregateIterator {
            source_iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            source_schema: Schema,
            group_by: Vec<Expr>,
            aggrs: Vec<AggregateExpr>,
            temp_dir: PathBuf,
            memory_budget: usize,
            output: Option<AggOutput>,
        }

        impl HashAggregateIterator {
            fn spill_groups(
                &self,
                groups: &mut HashMap<Vec<DbValue>, Vec<Accumulator>>,
                runs: &mut Vec<Run<Vec<Accumulator>>>,
            ) -> Result<(), String> {
                let directions = vec![true; self.group_by.len()];
                let mut entries: Vec<(Vec<DbValue>, Vec<Accumulator>)> = groups.drain().collect();
                spill::sort_entries(&mut entries, &directions);
                runs.push(spill::write_run(&self.temp_dir, "agg_run", &entries)?);
                Ok(())
            }
        }

        impl Iterator for HashAggregateIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                if self.output.is_none() {
                    let mut groups: HashMap<Vec<DbValue>, Vec<Accumulator>> = HashMap::new();
                    let mut buffer_bytes: usize = 0;
                    let mut runs: Vec<Run<Vec<Accumulator>>> = Vec::new();
                    let acc_overhead = self.aggrs.len() * std::mem::size_of::<Accumulator>();

                    while let Some(row_res) = self.source_iter.next() {
                        let row = match row_res {
                            Ok(r) => r,
                            Err(e) => return Some(Err(e)),
                        };

                        let mut group_vals = Vec::with_capacity(self.group_by.len());
                        for expr in &self.group_by {
                            match expr.eval(&row, &self.source_schema) {
                                Ok(val) => group_vals.push(val),
                                Err(e) => return Some(Err(e)),
                            }
                        }

                        let added = if groups.contains_key(&group_vals) {
                            0
                        } else {
                            spill::estimate_row_size(&group_vals, &[]) + acc_overhead
                        };
                        let accumulators = groups
                            .entry(group_vals)
                            .or_insert_with(|| new_accumulators(&self.aggrs));

                        for (idx, aggr) in self.aggrs.iter().enumerate() {
                            let val = match aggr {
                                AggregateExpr::Count { expr, .. }
                                | AggregateExpr::Sum { expr, .. }
                                | AggregateExpr::Min { expr, .. }
                                | AggregateExpr::Max { expr, .. }
                                | AggregateExpr::Avg { expr, .. } => {
                                    match expr.eval(&row, &self.source_schema) {
                                        Ok(v) => v,
                                        Err(e) => return Some(Err(e)),
                                    }
                                }
                            };
                            if let Err(e) = accumulators[idx].update(&val) {
                                return Some(Err(e));
                            }
                        }

                        buffer_bytes += added;
                        if buffer_bytes >= self.memory_budget && !self.group_by.is_empty() {
                            if let Err(e) = self.spill_groups(&mut groups, &mut runs) {
                                return Some(Err(e));
                            }
                            buffer_bytes = 0;
                        }
                    }

                    if runs.is_empty() {
                        if self.group_by.is_empty() && groups.is_empty() {
                            groups.insert(Vec::new(), new_accumulators(&self.aggrs));
                        }
                        let output_rows: Vec<Row> = match groups
                            .into_iter()
                            .map(|(keys, accs)| finalize_group(keys, accs))
                            .collect::<Result<_, String>>()
                        {
                            Ok(rows) => rows,
                            Err(e) => return Some(Err(e)),
                        };
                        self.output = Some(AggOutput::InMemory(output_rows.into_iter()));
                    } else {
                        if !groups.is_empty() {
                            let res = self.spill_groups(&mut groups, &mut runs);
                            if let Err(e) = res {
                                return Some(Err(e));
                            }
                        }
                        let merger = match KWayMerge::new(
                            runs,
                            vec![true; self.group_by.len()],
                            &self.temp_dir,
                            "agg_run",
                        ) {
                            Ok(m) => m,
                            Err(e) => return Some(Err(e)),
                        };
                        self.output = Some(AggOutput::Merge(AggMerge {
                            merger,
                            current: None,
                        }));
                    }
                }

                match self.output.as_mut().unwrap() {
                    AggOutput::InMemory(iter) => iter.next().map(Ok),
                    AggOutput::Merge(merge) => match merge.next() {
                        Ok(Some(row)) => Some(Ok(row)),
                        Ok(None) => None,
                        Err(e) => Some(Err(e)),
                    },
                }
            }
        }

        Ok(Box::new(HashAggregateIterator {
            source_iter,
            source_schema,
            group_by,
            aggrs,
            temp_dir: self.temp_dir.clone(),
            memory_budget: self.memory_budget,
            output: None,
        }))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalHashAggregate: group_by={:?}, aggrs={:?}\n",
            "  ".repeat(indent),
            self.group_by,
            self.aggrs
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// 7.5. SortedAggregate Physical Operator (Streaming)
// ==========================================
pub struct PhysicalSortedAggregate {
    source: Box<dyn PhysicalOperator>,
    group_by: Vec<Expr>,
    aggrs: Vec<AggregateExpr>,
    schema: Schema,
}

impl PhysicalSortedAggregate {
    pub fn new(
        source: Box<dyn PhysicalOperator>,
        group_by: Vec<Expr>,
        aggrs: Vec<AggregateExpr>,
        schema: Schema,
    ) -> Self {
        Self {
            source,
            group_by,
            aggrs,
            schema,
        }
    }
}

impl PhysicalOperator for PhysicalSortedAggregate {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let source_iter = self.source.execute(tx, params)?;
        let source_schema = self.source.schema().clone();

        let mut group_by = self.group_by.clone();
        for expr in &mut group_by {
            expr.substitute_params(params)?;
        }
        let mut aggrs = self.aggrs.clone();
        for aggr in &mut aggrs {
            match aggr {
                AggregateExpr::Count { expr, .. }
                | AggregateExpr::Sum { expr, .. }
                | AggregateExpr::Min { expr, .. }
                | AggregateExpr::Max { expr, .. }
                | AggregateExpr::Avg { expr, .. } => {
                    expr.substitute_params(params)?;
                }
            }
        }

        struct SortedAggregateIterator {
            source_iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            source_schema: Schema,
            group_by: Vec<Expr>,
            aggrs: Vec<AggregateExpr>,
            active_group_keys: Option<Vec<DbValue>>,
            active_accumulators: Vec<Accumulator>,
            next_row: Option<Row>,
            source_exhausted: bool,
        }

        impl Iterator for SortedAggregateIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                if self.next_row.is_none() && !self.source_exhausted {
                    match self.source_iter.next() {
                        Some(Ok(row)) => {
                            self.next_row = Some(row);
                        }
                        Some(Err(e)) => return Some(Err(e)),
                        None => {
                            self.source_exhausted = true;
                            if self.group_by.is_empty() && self.active_group_keys.is_none() {
                                self.active_group_keys = Some(Vec::new());
                                self.active_accumulators = new_accumulators(&self.aggrs);
                            }
                        }
                    }
                }

                loop {
                    let row = match self.next_row.take() {
                        Some(r) => r,
                        None => {
                            if let Some(keys) = self.active_group_keys.take() {
                                let mut row_vals = keys;
                                for acc in self.active_accumulators.drain(..) {
                                    match acc.finalize() {
                                        Ok(val) => row_vals.push(val),
                                        Err(e) => return Some(Err(e)),
                                    }
                                }
                                return Some(Ok(Row::new(row_vals)));
                            }
                            return None;
                        }
                    };

                    let mut group_vals = Vec::with_capacity(self.group_by.len());
                    for expr in &self.group_by {
                        match expr.eval(&row, &self.source_schema) {
                            Ok(val) => group_vals.push(val),
                            Err(e) => return Some(Err(e)),
                        }
                    }

                    if let Some(active_keys) = &self.active_group_keys {
                        if group_vals == *active_keys {
                            for (idx, aggr) in self.aggrs.iter().enumerate() {
                                let val = match aggr {
                                    AggregateExpr::Count { expr, .. }
                                    | AggregateExpr::Sum { expr, .. }
                                    | AggregateExpr::Min { expr, .. }
                                    | AggregateExpr::Max { expr, .. }
                                    | AggregateExpr::Avg { expr, .. } => {
                                        match expr.eval(&row, &self.source_schema) {
                                            Ok(v) => v,
                                            Err(e) => return Some(Err(e)),
                                        }
                                    }
                                };
                                if let Err(e) = self.active_accumulators[idx].update(&val) {
                                    return Some(Err(e));
                                }
                            }

                            match self.source_iter.next() {
                                Some(Ok(row)) => {
                                    self.next_row = Some(row);
                                }
                                Some(Err(e)) => return Some(Err(e)),
                                None => {
                                    self.source_exhausted = true;
                                }
                            }
                        } else {
                            self.next_row = Some(row);

                            let keys = self.active_group_keys.take().unwrap();
                            let mut row_vals = keys;
                            for acc in self.active_accumulators.drain(..) {
                                match acc.finalize() {
                                    Ok(val) => row_vals.push(val),
                                    Err(e) => return Some(Err(e)),
                                }
                            }
                            return Some(Ok(Row::new(row_vals)));
                        }
                    } else {
                        self.active_group_keys = Some(group_vals);
                        self.active_accumulators = new_accumulators(&self.aggrs);

                        for (idx, aggr) in self.aggrs.iter().enumerate() {
                            let val = match aggr {
                                AggregateExpr::Count { expr, .. }
                                | AggregateExpr::Sum { expr, .. }
                                | AggregateExpr::Min { expr, .. }
                                | AggregateExpr::Max { expr, .. }
                                | AggregateExpr::Avg { expr, .. } => {
                                    match expr.eval(&row, &self.source_schema) {
                                        Ok(v) => v,
                                        Err(e) => return Some(Err(e)),
                                    }
                                }
                            };
                            if let Err(e) = self.active_accumulators[idx].update(&val) {
                                return Some(Err(e));
                            }
                        }

                        match self.source_iter.next() {
                            Some(Ok(row)) => {
                                self.next_row = Some(row);
                            }
                            Some(Err(e)) => return Some(Err(e)),
                            None => {
                                self.source_exhausted = true;
                            }
                        }
                    }
                }
            }
        }

        Ok(Box::new(SortedAggregateIterator {
            source_iter,
            source_schema,
            group_by,
            aggrs,
            active_group_keys: None,
            active_accumulators: Vec::new(),
            next_row: None,
            source_exhausted: false,
        }))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSortedAggregate: group_by={:?}, aggrs={:?}\n",
            "  ".repeat(indent),
            self.group_by,
            self.aggrs
        ));
        self.source.explain(indent + 1, out);
    }
}

// ==========================================
// Aggregation State Accumulators
// ==========================================
#[derive(Clone, serde::Serialize, serde::Deserialize)]
enum Accumulator {
    Count {
        count: i64,
    },
    // Track integer and floating-point running totals separately so SUM(int_col)
    // can finalize as Int when no Float input is ever observed, matching the
    // schema declared by the logical planner. We only fall back to Float if a
    // Float input appears or if the integer accumulator would overflow.
    Sum {
        int_sum: Option<i64>,
        float_sum: Option<f64>,
        // Stringified for spill serialization: rust_decimal's default serde uses
        // `deserialize_any`, which postcard (the spill format) cannot decode.
        #[serde(with = "dtdb_storage::decimal_serde_option")]
        decimal_sum: Option<rust_decimal::Decimal>,
    },
    Min {
        min: Option<DbValue>,
    },
    Max {
        max: Option<DbValue>,
    },
    Avg {
        sum: f64,
        count: i64,
        #[serde(with = "dtdb_storage::decimal_serde_option")]
        decimal_sum: Option<rust_decimal::Decimal>,
    },
    // DISTINCT aggregate (COUNT/SUM/AVG DISTINCT). Inputs are collected into
    // `seen`, deduplicated by value, and the wrapped `inner` aggregate is applied
    // to the distinct set only at finalize time. Deferring aggregation keeps
    // merging of spilled partial groups a simple set union: the same value may
    // appear in several runs of one group, so partial inner results cannot be
    // combined directly without double counting.
    Distinct {
        seen: HashSet<DbValue>,
        inner: Box<Accumulator>,
    },
}

/// Builds a fresh zeroed accumulator for a single aggregate expression, wrapping
/// it in a `Distinct` layer when the call used the `DISTINCT` quantifier. MIN/MAX
/// are idempotent under duplication, so DISTINCT is a no-op there and skipped.
fn make_accumulator(aggr: &AggregateExpr) -> Accumulator {
    let (base, distinct) = match aggr {
        AggregateExpr::Count { distinct, .. } => (Accumulator::Count { count: 0 }, *distinct),
        AggregateExpr::Sum { distinct, .. } => (
            Accumulator::Sum {
                int_sum: None,
                float_sum: None,
                decimal_sum: None,
            },
            *distinct,
        ),
        AggregateExpr::Avg { distinct, .. } => (
            Accumulator::Avg {
                sum: 0.0,
                count: 0,
                decimal_sum: None,
            },
            *distinct,
        ),
        AggregateExpr::Min { .. } => (Accumulator::Min { min: None }, false),
        AggregateExpr::Max { .. } => (Accumulator::Max { max: None }, false),
    };
    if distinct {
        Accumulator::Distinct {
            seen: HashSet::new(),
            inner: Box::new(base),
        }
    } else {
        base
    }
}

/// Creates a fresh set of zeroed accumulators matching the given aggregate exprs.
fn new_accumulators(aggrs: &[AggregateExpr]) -> Vec<Accumulator> {
    aggrs.iter().map(make_accumulator).collect()
}

/// Builds an output row from group keys followed by each finalized aggregate.
fn finalize_group(keys: Vec<DbValue>, accs: Vec<Accumulator>) -> Result<Row, String> {
    let mut row_vals = keys;
    for acc in accs {
        row_vals.push(acc.finalize()?);
    }
    Ok(Row::new(row_vals))
}

impl Accumulator {
    fn update(&mut self, val: &DbValue) -> Result<(), String> {
        if matches!(val, DbValue::Null) {
            return Ok(()); // Ignore NULL values for all aggregates
        }
        match self {
            // Defer the underlying aggregation to finalize; here we only record the
            // distinct input values. The NULL guard above already excludes NULLs.
            Accumulator::Distinct { seen, .. } => {
                seen.insert(val.clone());
            }
            Accumulator::Count { count } => {
                *count += 1;
            }
            Accumulator::Sum {
                int_sum,
                float_sum,
                decimal_sum,
            } => match val {
                DbValue::Decimal(v) => {
                    if let Some(dec) = decimal_sum {
                        *decimal_sum = Some(*dec + *v);
                    } else {
                        let current = int_sum.take().unwrap_or(0);
                        *decimal_sum = Some(rust_decimal::Decimal::from(current) + *v);
                    }
                }
                DbValue::Int(v) => {
                    if let Some(dec) = decimal_sum {
                        *decimal_sum = Some(*dec + rust_decimal::Decimal::from(*v));
                    } else if float_sum.is_some() {
                        *float_sum.as_mut().unwrap() += *v as f64;
                    } else {
                        let current = int_sum.unwrap_or(0);
                        match current.checked_add(*v) {
                            Some(new_sum) => *int_sum = Some(new_sum),
                            None => {
                                let promoted = current as f64 + *v as f64;
                                *int_sum = None;
                                *float_sum = Some(promoted);
                            }
                        }
                    }
                }
                DbValue::Float(v) => {
                    if let Some(dec) = decimal_sum.take() {
                        let dec_f = dec.to_f64().unwrap_or(0.0);
                        *float_sum = Some(dec_f + *v);
                    } else {
                        let promoted =
                            float_sum.unwrap_or(0.0) + int_sum.take().unwrap_or(0) as f64;
                        *float_sum = Some(promoted + *v);
                    }
                }
                other => {
                    return Err(format!(
                        "Cannot compute SUM on non-numeric value {:?}",
                        other
                    ));
                }
            },
            Accumulator::Min { min } => match min {
                Some(m) => {
                    let ord = compare_values(val, m)?;
                    if ord == std::cmp::Ordering::Less {
                        *min = Some(val.clone());
                    }
                }
                None => *min = Some(val.clone()),
            },
            Accumulator::Max { max } => match max {
                Some(m) => {
                    let ord = compare_values(val, m)?;
                    if ord == std::cmp::Ordering::Greater {
                        *max = Some(val.clone());
                    }
                }
                None => *max = Some(val.clone()),
            },
            Accumulator::Avg {
                sum,
                count,
                decimal_sum,
            } => {
                match val {
                    DbValue::Decimal(v) => {
                        if let Some(dec) = decimal_sum {
                            *decimal_sum = Some(*dec + *v);
                        } else {
                            if *count > 0 {
                                if let Some(dec_prev) = rust_decimal::Decimal::from_f64(*sum) {
                                    *decimal_sum = Some(dec_prev + *v);
                                } else {
                                    *sum += v.to_f64().unwrap_or(0.0);
                                }
                            } else {
                                *decimal_sum = Some(*v);
                            }
                        }
                    }
                    DbValue::Int(v) => {
                        if let Some(dec) = decimal_sum {
                            *decimal_sum = Some(*dec + rust_decimal::Decimal::from(*v));
                        } else {
                            *sum += *v as f64;
                        }
                    }
                    DbValue::Float(v) => {
                        if let Some(dec) = decimal_sum.take() {
                            *sum = dec.to_f64().unwrap_or(0.0) + *v;
                        } else {
                            *sum += *v;
                        }
                    }
                    other => {
                        return Err(format!(
                            "Cannot compute AVG on non-numeric value {:?}",
                            other
                        ));
                    }
                }
                *count += 1;
            }
        }
        Ok(())
    }

    /// Combines a partial accumulator (from a spilled run) into this one. Both
    /// must be the same variant, which holds because they aggregate the same
    /// group across runs.
    fn merge(&mut self, other: Accumulator) -> Result<(), String> {
        match (self, other) {
            (Accumulator::Count { count }, Accumulator::Count { count: o }) => {
                *count += o;
            }
            (
                Accumulator::Sum {
                    int_sum,
                    float_sum,
                    decimal_sum,
                },
                Accumulator::Sum {
                    int_sum: o_int,
                    float_sum: o_float,
                    decimal_sum: o_dec,
                },
            ) => {
                if decimal_sum.is_some() || o_dec.is_some() {
                    let a = decimal_sum.unwrap_or(rust_decimal::Decimal::ZERO)
                        + rust_decimal::Decimal::from(int_sum.take().unwrap_or(0));
                    let b = o_dec.unwrap_or(rust_decimal::Decimal::ZERO)
                        + rust_decimal::Decimal::from(o_int.unwrap_or(0));
                    *decimal_sum = Some(a + b);
                } else if float_sum.is_some() || o_float.is_some() {
                    let a = float_sum.unwrap_or(0.0) + int_sum.take().unwrap_or(0) as f64;
                    let b = o_float.unwrap_or(0.0) + o_int.unwrap_or(0) as f64;
                    *float_sum = Some(a + b);
                } else {
                    match (*int_sum, o_int) {
                        (None, None) => {}
                        (Some(a), None) => *int_sum = Some(a),
                        (None, Some(b)) => *int_sum = Some(b),
                        (Some(a), Some(b)) => match a.checked_add(b) {
                            Some(s) => *int_sum = Some(s),
                            None => {
                                *int_sum = None;
                                *float_sum = Some(a as f64 + b as f64);
                            }
                        },
                    }
                }
            }
            (Accumulator::Min { min }, Accumulator::Min { min: o }) => {
                if let Some(v) = o {
                    match min {
                        Some(cur) if compare_values(&v, cur)? != std::cmp::Ordering::Less => {}
                        _ => *min = Some(v),
                    }
                }
            }
            (Accumulator::Max { max }, Accumulator::Max { max: o }) => {
                if let Some(v) = o {
                    match max {
                        Some(cur) if compare_values(&v, cur)? != std::cmp::Ordering::Greater => {}
                        _ => *max = Some(v),
                    }
                }
            }
            (
                Accumulator::Avg {
                    sum,
                    count,
                    decimal_sum,
                },
                Accumulator::Avg {
                    sum: o_sum,
                    count: o_count,
                    decimal_sum: o_dec,
                },
            ) => {
                if decimal_sum.is_some() || o_dec.is_some() {
                    let a = decimal_sum.unwrap_or(rust_decimal::Decimal::ZERO);
                    let b = o_dec.unwrap_or(rust_decimal::Decimal::ZERO);
                    *decimal_sum = Some(a + b);
                } else {
                    *sum += o_sum;
                }
                *count += o_count;
            }
            // Partial distinct groups from different spilled runs may share values,
            // so the inner aggregate is rebuilt from the union at finalize; merging
            // is just the set union of observed values.
            (Accumulator::Distinct { seen, .. }, Accumulator::Distinct { seen: o_seen, .. }) => {
                seen.extend(o_seen);
            }
            _ => return Err("Cannot merge accumulators of different kinds".to_string()),
        }
        Ok(())
    }

    fn finalize(&self) -> Result<DbValue, String> {
        let val = match self {
            Accumulator::Count { count } => DbValue::Int(*count),
            Accumulator::Sum {
                int_sum,
                float_sum,
                decimal_sum,
            } => {
                if let Some(dec) = decimal_sum {
                    DbValue::Decimal(*dec)
                } else {
                    match (float_sum, int_sum) {
                        (Some(f), _) => DbValue::Float(*f),
                        (None, Some(i)) => DbValue::Int(*i),
                        (None, None) => DbValue::Null,
                    }
                }
            }
            Accumulator::Min { min } => min.clone().unwrap_or(DbValue::Null),
            Accumulator::Max { max } => max.clone().unwrap_or(DbValue::Null),
            Accumulator::Avg {
                sum,
                count,
                decimal_sum,
            } => {
                if *count == 0 {
                    DbValue::Null
                } else if let Some(dec) = decimal_sum {
                    let count_dec = rust_decimal::Decimal::from(*count);
                    DbValue::Decimal(*dec / count_dec)
                } else {
                    DbValue::Float(*sum / (*count as f64))
                }
            }
            // Replay the deduplicated values through a fresh copy of the wrapped
            // aggregate. Set iteration order is unspecified, which is fine: the
            // wrapped aggregates here (COUNT/SUM/AVG) are order-insensitive.
            Accumulator::Distinct { seen, inner } => {
                let mut acc = (**inner).clone();
                for v in seen {
                    acc.update(v)?;
                }
                acc.finalize()?
            }
        };
        Ok(val)
    }
}

// ==========================================
// Helper Utility Functions
// ==========================================
// compare_values is imported from crate::expr::compare_// ==========================================
// Set Operation Physical Operator (UNION, INTERSECT, EXCEPT)
// ==========================================
/// A peekable stream of rows in total-order, produced by externally sorting a child
/// operator. Memory is bounded by spilling sorted runs; `head` holds the current row.
struct SortedRowStream {
    inner: SortedStreamInner,
    head: Option<Vec<DbValue>>,
}

enum SortedStreamInner {
    InMemory(std::vec::IntoIter<Vec<DbValue>>),
    External(KWayMerge<()>),
}

impl SortedRowStream {
    fn build(
        source: &mut dyn Iterator<Item = Result<Row, String>>,
        source_schema: &Schema,
        temp_dir: &std::path::Path,
        memory_budget: usize,
    ) -> Result<Self, String> {
        let directions = vec![true; source_schema.columns.len()];
        let mut buffer: Vec<(Vec<DbValue>, ())> = Vec::new();
        let mut buffer_bytes: usize = 0;
        let mut runs: Vec<Run<()>> = Vec::new();

        for row_res in source {
            let row = row_res?;
            let key = row.values;
            buffer_bytes += spill::estimate_row_size(&key, &[]);
            buffer.push((key, ()));
            if buffer_bytes >= memory_budget {
                spill::sort_entries(&mut buffer, &directions);
                runs.push(spill::write_run(temp_dir, "setop_run", &buffer)?);
                buffer.clear();
                buffer_bytes = 0;
            }
        }

        let inner = if runs.is_empty() {
            spill::sort_entries(&mut buffer, &directions);
            SortedStreamInner::InMemory(
                buffer
                    .into_iter()
                    .map(|(k, _)| k)
                    .collect::<Vec<_>>()
                    .into_iter(),
            )
        } else {
            if !buffer.is_empty() {
                spill::sort_entries(&mut buffer, &directions);
                runs.push(spill::write_run(temp_dir, "setop_run", &buffer)?);
            }
            SortedStreamInner::External(KWayMerge::new(runs, directions, temp_dir, "setop_run")?)
        };

        let mut stream = Self { inner, head: None };
        stream.advance()?;
        Ok(stream)
    }

    fn advance(&mut self) -> Result<(), String> {
        self.head = match &mut self.inner {
            SortedStreamInner::InMemory(iter) => iter.next(),
            SortedStreamInner::External(merger) => merger.next()?.map(|(k, _)| k),
        };
        Ok(())
    }

    fn peek(&self) -> Option<&Vec<DbValue>> {
        self.head.as_ref()
    }

    /// Consumes and counts the rows at the head equal to `key`, advancing past them.
    fn consume_equal(&mut self, key: &[DbValue]) -> Result<usize, String> {
        let mut count = 0;
        while let Some(head) = self.head.as_deref() {
            if compare_rows(head, key) == std::cmp::Ordering::Equal {
                count += 1;
                self.advance()?;
            } else {
                break;
            }
        }
        Ok(count)
    }
}

/// Total-order comparison of two whole rows (all columns ascending).
fn compare_rows(a: &[DbValue], b: &[DbValue]) -> std::cmp::Ordering {
    for (x, y) in a.iter().zip(b.iter()) {
        let ord = spill::total_compare(x, y);
        if ord != std::cmp::Ordering::Equal {
            return ord;
        }
    }
    a.len().cmp(&b.len())
}

pub struct PhysicalSetOp {
    left: Box<dyn PhysicalOperator>,
    right: Box<dyn PhysicalOperator>,
    op: SetOpType,
    all: bool,
    schema: Schema,
    temp_dir: PathBuf,
    memory_budget: usize,
}

impl PhysicalSetOp {
    pub fn new(
        left: Box<dyn PhysicalOperator>,
        right: Box<dyn PhysicalOperator>,
        op: SetOpType,
        all: bool,
        schema: Schema,
        temp_dir: PathBuf,
        memory_budget: usize,
    ) -> Self {
        Self {
            left,
            right,
            op,
            all,
            schema,
            temp_dir,
            memory_budget,
        }
    }
}

/// Number of times the row for the current key should be emitted, given the
/// occurrence counts on each side and the operation's multiset semantics.
fn set_op_emit_count(op: &SetOpType, all: bool, left_count: usize, right_count: usize) -> usize {
    match op {
        SetOpType::Union => {
            if all {
                left_count + right_count
            } else {
                usize::from(left_count + right_count > 0)
            }
        }
        SetOpType::Intersect => {
            if all {
                left_count.min(right_count)
            } else {
                usize::from(left_count > 0 && right_count > 0)
            }
        }
        SetOpType::Except => {
            if all {
                left_count.saturating_sub(right_count)
            } else {
                usize::from(left_count > 0 && right_count == 0)
            }
        }
    }
}

impl PhysicalOperator for PhysicalSetOp {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let left_iter = self.left.execute(tx, params)?;
        let right_iter = self.right.execute(tx, params)?;
        let left_schema = self.left.schema().clone();
        let right_schema = self.right.schema().clone();

        struct SetOpIterator {
            left_iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            right_iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            left_schema: Schema,
            right_schema: Schema,
            op: SetOpType,
            all: bool,
            temp_dir: PathBuf,
            memory_budget: usize,
            streams: Option<(SortedRowStream, SortedRowStream)>,
            pending: std::collections::VecDeque<Vec<DbValue>>,
        }

        impl Iterator for SetOpIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                if self.streams.is_none() {
                    let left = match SortedRowStream::build(
                        &mut *self.left_iter,
                        &self.left_schema,
                        &self.temp_dir,
                        self.memory_budget,
                    ) {
                        Ok(s) => s,
                        Err(e) => return Some(Err(e)),
                    };
                    let right = match SortedRowStream::build(
                        &mut *self.right_iter,
                        &self.right_schema,
                        &self.temp_dir,
                        self.memory_budget,
                    ) {
                        Ok(s) => s,
                        Err(e) => return Some(Err(e)),
                    };
                    self.streams = Some((left, right));
                }

                let op = self.op;
                let all = self.all;
                let (left, right) = self.streams.as_mut().unwrap();

                loop {
                    if let Some(row) = self.pending.pop_front() {
                        return Some(Ok(Row::new(row)));
                    }

                    // Pick the smaller of the two current heads as the next group key.
                    let key = match (left.peek(), right.peek()) {
                        (None, None) => return None,
                        (Some(l), None) => l.clone(),
                        (None, Some(r)) => r.clone(),
                        (Some(l), Some(r)) => {
                            if compare_rows(l, r) == std::cmp::Ordering::Greater {
                                r.clone()
                            } else {
                                l.clone()
                            }
                        }
                    };

                    let left_count = match left.consume_equal(&key) {
                        Ok(c) => c,
                        Err(e) => return Some(Err(e)),
                    };
                    let right_count = match right.consume_equal(&key) {
                        Ok(c) => c,
                        Err(e) => return Some(Err(e)),
                    };

                    let emit = set_op_emit_count(&op, all, left_count, right_count);
                    for _ in 0..emit {
                        self.pending.push_back(key.clone());
                    }
                }
            }
        }

        Ok(Box::new(SetOpIterator {
            left_iter,
            right_iter,
            left_schema,
            right_schema,
            op: self.op,
            all: self.all,
            temp_dir: self.temp_dir.clone(),
            memory_budget: self.memory_budget,
            streams: None,
            pending: std::collections::VecDeque::new(),
        }))
    }

    fn schema(&self) -> &Schema {
        &self.schema
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!(
            "{}- PhysicalSetOp: op={:?}, all={}\n",
            "  ".repeat(indent),
            self.op,
            self.all
        ));
        out.push_str(&format!("{}  left:\n", "  ".repeat(indent)));
        self.left.explain(indent + 2, out);
        out.push_str(&format!("{}  right:\n", "  ".repeat(indent)));
        self.right.explain(indent + 2, out);
    }
}

// ==========================================
// 9. Distinct Physical Operator (Sort-based, bounded-memory)
// ==========================================
/// Deduplicates by externally sorting the source on all columns, then dropping
/// rows equal to the previously emitted one. Memory is bounded by spilling sorted
/// runs; equal rows are adjacent after the merge so a single look-back suffices.
pub struct PhysicalDistinct {
    source: Box<dyn PhysicalOperator>,
    temp_dir: PathBuf,
    memory_budget: usize,
}

enum DistinctState {
    InMemory(std::vec::IntoIter<Vec<DbValue>>),
    External {
        merger: KWayMerge<()>,
        last: Option<Vec<DbValue>>,
    },
}

impl PhysicalDistinct {
    pub fn new(source: Box<dyn PhysicalOperator>, temp_dir: PathBuf, memory_budget: usize) -> Self {
        Self {
            source,
            temp_dir,
            memory_budget,
        }
    }
}

impl PhysicalOperator for PhysicalDistinct {
    fn execute(
        &self,
        tx: &Transaction,
        params: &HashMap<String, DbValue>,
    ) -> Result<Box<dyn Iterator<Item = Result<Row, String>> + Send>, String> {
        let source_iter = self.source.execute(tx, params)?;
        let source_schema = self.source.schema().clone();

        struct DistinctIterator {
            source_iter: Box<dyn Iterator<Item = Result<Row, String>> + Send>,
            source_schema: Schema,
            temp_dir: PathBuf,
            memory_budget: usize,
            state: Option<DistinctState>,
        }

        impl Iterator for DistinctIterator {
            type Item = Result<Row, String>;

            fn next(&mut self) -> Option<Self::Item> {
                if self.state.is_none() {
                    let width = self.source_schema.columns.len();
                    let directions = vec![true; width];
                    let mut buffer: Vec<(Vec<DbValue>, ())> = Vec::new();
                    let mut buffer_bytes: usize = 0;
                    let mut runs: Vec<Run<()>> = Vec::new();

                    for row_res in self.source_iter.by_ref() {
                        let row = match row_res {
                            Ok(r) => r,
                            Err(e) => return Some(Err(e)),
                        };
                        let key = row.values;
                        buffer_bytes += spill::estimate_row_size(&key, &[]);
                        buffer.push((key, ()));

                        if buffer_bytes >= self.memory_budget {
                            spill::sort_entries(&mut buffer, &directions);
                            match spill::write_run(&self.temp_dir, "distinct_run", &buffer) {
                                Ok(run) => runs.push(run),
                                Err(e) => return Some(Err(e)),
                            }
                            buffer.clear();
                            buffer_bytes = 0;
                        }
                    }

                    if runs.is_empty() {
                        spill::sort_entries(&mut buffer, &directions);
                        let mut keys: Vec<Vec<DbValue>> =
                            buffer.into_iter().map(|(k, _)| k).collect();
                        keys.dedup();
                        self.state = Some(DistinctState::InMemory(keys.into_iter()));
                    } else {
                        if !buffer.is_empty() {
                            spill::sort_entries(&mut buffer, &directions);
                            match spill::write_run(&self.temp_dir, "distinct_run", &buffer) {
                                Ok(run) => runs.push(run),
                                Err(e) => return Some(Err(e)),
                            }
                        }
                        let merger = match KWayMerge::new(
                            runs,
                            directions,
                            &self.temp_dir,
                            "distinct_run",
                        ) {
                            Ok(m) => m,
                            Err(e) => return Some(Err(e)),
                        };
                        self.state = Some(DistinctState::External { merger, last: None });
                    }
                }

                match self.state.as_mut().unwrap() {
                    DistinctState::InMemory(iter) => Ok(iter.next().map(Row::new)).transpose(),
                    DistinctState::External { merger, last } => {
                        // Skip consecutive duplicates; equal keys are adjacent post-merge.
                        loop {
                            match merger.next() {
                                Ok(Some((key, ()))) => {
                                    if last.as_ref() != Some(&key) {
                                        *last = Some(key.clone());
                                        return Some(Ok(Row::new(key)));
                                    }
                                }
                                Ok(None) => return None,
                                Err(e) => return Some(Err(e)),
                            }
                        }
                    }
                }
            }
        }

        Ok(Box::new(DistinctIterator {
            source_iter,
            source_schema,
            temp_dir: self.temp_dir.clone(),
            memory_budget: self.memory_budget,
            state: None,
        }))
    }

    fn schema(&self) -> &Schema {
        self.source.schema()
    }

    fn explain(&self, indent: usize, out: &mut String) {
        out.push_str(&format!("{}- PhysicalDistinct\n", "  ".repeat(indent)));
        self.source.explain(indent + 1, out);
    }
}
