name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  tsan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust Nightly
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rust-src

    - name: Run tests with ThreadSanitizer
      env:
        RUSTFLAGS: "-Z sanitizer=thread"
        RUSTDOCFLAGS: "-Z sanitizer=thread"
      run: cargo test -Zbuild-std --target x86_64-unknown-linux-gnu --verbose
