name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - uses: Swatinem/rust-cache@v2

    - name: Install Protocol Buffers Compiler
      uses: arduino/setup-protoc@v3

    - name: Check formatting
      run: cargo fmt --check

    - name: Clippy
      env:
        RUSTFLAGS: "-D warnings"
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      env:
        RUSTFLAGS: "-D warnings"
      run: cargo test --verbose

    - name: Bench smoke
      run: cargo bench --no-run

  tsan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust Nightly
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rust-src

    - uses: Swatinem/rust-cache@v2

    - name: Install Protocol Buffers Compiler
      uses: arduino/setup-protoc@v3

    - name: Run tests with ThreadSanitizer
      run: ./scripts/run_tsan.sh
